insert into movies values (	'M00001', 'The Godfather', '1972', 'Action / Crime / Drama',  8.6, 175, 'USA', 'English', 'Color', 'DTS/Mono', 'R');
insert into movies values (	'M00002', 'The Shawshank Redemption', '1994', 'Drama / Mystery / Thriller',  8.7, 142, 'USA', 'English', 'Color', 'Dolby Digital/SDDS', 'R');
insert into movies values (	'M00003', 'Schindlers List', '1993', 'Drama / War', 8.5, 197, 'USA', 'English/Hebrew', 'Black and White', 'DTS', 'R' );
insert into movies values (	'M00004', 'Star Wars',  '1977', 'Action / Adventure / Drama', 8.8, 121, 'USA', 'English', 'Color', 'DTS/Dolby Digital/SDDS', 'PG' );
insert into movies values (	'M00005', 'Saving Private Ryan', '1998', 'Action', 8.9, 170, 'USA', 'English', 'Color', 'DTS/Dolby Digital/SDDS', 'R' );
insert into movies values (	'M00006', 'Casablanca',  '1942', 'Drama / Romance / War', 8.6, 102, 'USA', 'English', 'Black and White', 'Mono', 'S');
insert into movies values (	'M00007', 'Citizen Kane',  '1941', 'Drama', 8.5, 119, 'USA', 'English', 'Black and White', 'Mono', 'U');
insert into movies values (	'M00008', 'One Flew Over the Cuckoos Nest', '1975', 'Drama', 8.5, 129, 'USA', 'English', 'Color', 'Dolby', 'R' );
insert into movies values (	'M00009', 'The Usual Suspects', '1995', 'Crime / Film-Noir / Thriller', 8.5, 106, 'USA', 'English', 'Color', 'Dolby Digital', 'R' );
insert into movies values (	'M00010', 'Raiders of the Lost Ark', '1981', 'Action / Adventure', 8.3, 115,  'USA', 'English', 'Color', 'Dolby', 'PG');
insert into movies values (	'M00011', 'The Godfather: Part II', '1974', 'Action / Crime / Drama', 8.4, 200,  'USA', 'English/Italian', 'Color', 'Mono', 'R');
insert into movies values (	'M00012', 'Rear Window', '1954', 'Thriller', 8.4, 113, 'USA', 'English', 'Color', 'Western Electric Sound System', 'K-8');
insert into movies values (	'M00013', 'The Empire Strikes Back', '1980', 'Action / Adventure / Drama / Romance / Sci-Fi / War',  8.4, 124, 'USA', 'English', 'Color', 'DTS/Dolby Digital/SDDS', 'PG');
insert into movies values (	'M00014', 'Dr. Strangelove', '1964', 'Sci-Fi / War', 8.5,  102, 'UK', 'English', 'Black and White', 'Mono', 'K-16' );
insert into movies values (	'M00015', 'North by Northwest', '1959', 'Mystery / Thriller', 8.4,  136, 'USA', 'English', 'Color', 'Mono', 'PG' );
insert into movies values (	'M00016', 'L.A. Confidential', '1997', 'Action / Crime / Drama / Film-Noir / Mystery / Thriller', 8.4, 136, 'USA', 'English', 'Color', 'DTS/Dolby Digital', 	'R');
insert into movies values (	'M00017', 'Psycho', '1960', 'Horror / Romance / Thriller', 8.3, 109, 'USA', 'English', 'Black and White', 'Westrex', 'R');
insert into movies values (	'M00018', 'The Silence of the Lambs', '1991', 'Thriller', 8.2, 118, 'USA', 'English', 'Color', 'Dolby SR', 'R' );
insert into movies values (	'M00019', 'To Kill a Mockingbird', '1962', 'Drama', 8.4, 129, 'USA', 'English', 'Black and White', 'Mono',  'Sweden:15' );
insert into movies values (	'M00020', 'Vertigo', '1958', 'Mystery / Thriller',  8.3,  128, 'USA', 'English', 'Color',  'DTS', 'France U');
insert into movies values (	'M00021', 'Taxi Driver', '1976',  'Drama', 8.3, 113, 'USA', 'English', 'Color', 'Dolby SR', 'R'  );
insert into movies values (	'M00022', 'Pulp Fiction', '1994', 'Comedy / Crime / Drama',  8.3, 154, 'USA', 'English', 'Color', 'Dolby Digital', 'R');
insert into movies values (	'M00023', '12 Angry Men', '1957', 'Drama',  8.4, 92, 'USA', 'English', 'Black and White', 'Mono', 'UK:U' );
insert into movies values (	'M00024', 'The Maltese Falcon', '1941', 'Film-Noir / Mystery', 8.2, 101, 'USA', 'English', 'Black and White',  'Mono',  'PG');
insert into movies values (	'M00025', 'Its a Wonderful Life', '1946', 'Drama', 8.3, 129, 'USA', 'English', 'Black and White', 'Mono', 'UK:U' );
insert into movies values (	'M00026', 'Lawrence of Arabia', '1962', 'Adventure / War', 8.3, 187, 'UK', 'English', 'Color', 'Dolby SR/Mono', 'PG');
insert into movies values (	'M00027', 'GoodFellas',  '1990', 'Crime / Drama', 8.3,  146, 'USA', 'English', 'Color', 'Dolby SR', 'R' );
insert into movies values (	'M00028', 'Good Will Hunting', '1997', 'Comedy / Drama / Romance', 8.4, 126, 'USA', 'English', 'Color', 'Dolby Digital', 'R' );
insert into movies values (	'M00029', 'The Truman Show', '1998', 'Comedy / Drama / Romance',  8.2, 102, 'USA', 'English', 'Color', 'DTS/Dolby Digital', 'PG');
insert into movies values (	'M00030', 'Raging Bull',  '1980',  'Drama', 8.3, 129, 'USA', 'English', 'Black and White', 'Dolby', 'R');
insert into movies values (	'M00031', 'The Sting', '1973', 'Comedy / Crime',  8.2, 129, 'USA', 'English', 'Color', 'Westrex', 'PG' );
insert into movies values (	'M00032', 'Monty Python and the Holy Grail', '1974', 'Comedy', 8.3, 89, 'UK', 'English', 'Color', 'Mono', 'UK:15' );
insert into movies values (	'M00033', 'The Bridge on the River Kwai', '1957', 'Drama / War', 8.2, 155, 'UK', 'English', 'Color', 'Dolby SR/Mono', 'PG' );
insert into movies values (	'M00034', 'Apocalypse Now', '1979', 'Action / Drama / War', 8.2, 155, 'USA', 'English', 'Color', 'Dolby', 'R' );
insert into movies values (	'M00035', 'The Wizard of Oz', '1939', 'Adventure / Drama / Musical', 8.1, 101, 'USA', 'English', 'Black and White', 'DTS/Dolby Digital/Mono/SDDS/', 'G' );
insert into movies values (	'M00036', 'Blade Runner', '1982', 'Action / Drama / Film-Noir / Sci-Fi', 8.4, 117, 'USA', 'English/Hungarian', 'Color', 'Dolby', 'R' );
insert into movies values (	'M00037', 'The Wrong Trousers', '1993', 'Animation / Comedy / Thriller',  8.5, 30, 'UK', 'English', 'Color', 'Dolby', 'Portugal:M' );
insert into movies values (	'M00038', 'Singin in the Rain', '1952', 'Musical / Romance',  8.3, 103, 'USA', 'English', 'Color', 'Mono', 'UK:U');
insert into movies values (	'M00039', 'Chinatown', '1974', 'Film-Noir / Mystery / Thriller',  8.2, 131, 'USA', 'English', 'Color', 'Mono', 'R' );
insert into movies values (	'M00040', 'Amadeus', '1984', 'Drama / Mystery',  8.3, 158, 'USA', 'English', 'Color', 'Dolby', 'PG' );
insert into movies values (	'M00041', 'The Third Man', '1949', 'Mystery / Thriller',  8.3, 100, 'UK', 'English/German', 'Black and White', 'Mono', 'PG' );
insert into movies values (	'M00042', 'The African Queen', '1951', 'Action / Adventure / Romance / War', 8.1, 105, 'USA', 'English', 'Color', 'Western Electric Sound System', 'UK:U' );
insert into movies values (	'M00043', 'Alien', '1979', 'Horror / Sci-Fi / Thriller', 8.1, 117, 'USA', 'English', 'Color', 'Dolby', 'R' );
insert into movies values (	'M00044', 'Glory', '1989', 'Action / Drama / War', 8.2,  122, 'USA', 'English', 'Color', 'Dolby', 'R' );
insert into movies values (	'M00045', 'Return of the Jedi', '1983', 'Action / Adventure / Sci-Fi / War', 8.1, 134, 'USA', 'English', 'Color', 'DTS/Dolby Digital/SDDS', 'PG');
insert into movies values (	'M00046', 'Braveheart', '1995',  'Action / Adventure / Drama / Romance / War', 8.3, 177, 'USA', 'English', 'Color', 'DTS/Dolby Digital', 'R');
insert into movies values (	'M00047', 'Shichinin no samurai', '1954', 'Action / Drama', 8.6,  160, 'Japan', 'Japanese', 'Black and White', 'Mono', 'Finland:K-16');
insert into movies values (	'M00048', 'Reservoir Dogs', '1992', 'Crime / Thriller',  8.2, 99, 'USA', 'English', 'Color', 'Dolby', 'R');
insert into movies values (	'M00049', 'The Princess Bride',  '1987', 'Action / Adventure / Comedy / Romance', 8.3, 98, 'USA', 'English', 'Color', 'Dolby', 'PG');
insert into movies values (	'M00050', 'Das Boot', '1981', 'Action / Drama / War', 8.3, 210, 'West Germany', 'Germany', 'Color', 'Dolby/SDDS', 'R');
