insert into actors_actresses values (	'Y00001', 'Marlon Brando' );
insert into actors_actresses values (	'Y00002', 'Al Pacino');
insert into actors_actresses values (	'Y00003', 'James Caan');
insert into actors_actresses values (	'Y00004', 'Richard S. Castellano');
insert into actors_actresses values (	'Y00005', 'Tim Robbins');
insert into actors_actresses values (	'Y00006', 'Morgan Freeman' );
insert into actors_actresses values (	'Y00007', 'Bob Gunton');
insert into actors_actresses values (	'Y00008', 'William Sadler' );
insert into actors_actresses values (	'Y00009', 'Liam Neeson');
insert into actors_actresses values (	'Y00010', 'Ben Kingsley' );
insert into actors_actresses values (	'Y00011', 'Ralph Fiennes' );
insert into actors_actresses values (	'X00001', 'Caroline Goodall');
insert into actors_actresses values (	'Y00012', 'Mark Hamill' );
insert into actors_actresses values (	'Y00013', 'Harrison Ford');
insert into actors_actresses values (	'X00002', 'Carrie Fisher');
insert into actors_actresses values (	'Y00014', 'Peter Cushing' );
insert into actors_actresses values (	'Y00015', 'Tom Hanks' );
insert into actors_actresses values (	'Y00016', 'Tom Sizemore' );
insert into actors_actresses values (	'Y00017', 'Edward Burns (I)' );
insert into actors_actresses values (	'X00003', 'Barry Pepper');
insert into actors_actresses values (	'Y00018', 'Humphrey Bogart');
insert into actors_actresses values (	'X00004', 'Ingrid Bergman' );
insert into actors_actresses values (	'Y00019', 'Paul Henreid' );
insert into actors_actresses values (	'Y00020', 'Claude Rains' );
insert into actors_actresses values (	'Y00021', 'Joseph Cotten' );
insert into actors_actresses values (	'X00005', 'Dorothy Comingore' );
insert into actors_actresses values (	'Y00022', 'Agnes Moorehead');
insert into actors_actresses values (	'X00006', 'Ruth Warrick' );
insert into actors_actresses values (	'Y00023', 'Jack Nicholson' );
insert into actors_actresses values (	'X00007', 'Louise Fletcher');
insert into actors_actresses values (	'Y00024', 'William Redfield');
insert into actors_actresses values (	'Y00025', 'Michael Berryman' );
insert into actors_actresses values (	'Y00026', 'Stephen Baldwin');
insert into actors_actresses values (	'Y00027', 'Gabriel Byrne' );
insert into actors_actresses values (	'Y00028', 'Benicio Del Toro');
insert into actors_actresses values (	'Y00029', 'Kevin Pollak' );
insert into actors_actresses values (	'Y00030', 'Harrison Ford' );
insert into actors_actresses values (	'X00008', 'Karen Allen' );
insert into actors_actresses values (	'Y00031', 'Paul Freeman (I)');
insert into actors_actresses values (	'Y00032', 'Ronald Lacey' );
insert into actors_actresses values (	'Y00033', 'Al Pacino' );
insert into actors_actresses values (	'Y00034', 'Robert Duvall' );
insert into actors_actresses values (	'X00009', 'Diane Keaton'	);
insert into actors_actresses values (	'Y00035', 'Robert De Niro' );
insert into actors_actresses values (	'Y00036', 'James Stewart' );
insert into actors_actresses values (	'X00010', 'Grace Kelly' );
insert into actors_actresses values (	'Y00037', 'Wendell Corey' );
insert into actors_actresses values (	'X00011', 'Thelma Ritter' );
insert into actors_actresses values (	'Y00038', 'Mark Hamill');
insert into actors_actresses values (	'Y00039', 'Harrison Ford'	);
insert into actors_actresses values (	'X00012', 'Carrie Fisher' );
insert into actors_actresses values (	'Y00040', 'Billy Dee Williams' );
insert into actors_actresses values (	'Y00041', 'Peter Sellers' );
insert into actors_actresses values (	'Y00042', 'George C. Scott');
insert into actors_actresses values (	'Y00043', 'Sterling Hayden');
insert into actors_actresses values (	'Y00044', 'Keenan Wynn' );
insert into actors_actresses values (	'Y00045', 'Cary Grant');
insert into actors_actresses values (	'Y00046', 'Eva Marie Saint' );
insert into actors_actresses values (	'Y00047', 'James Mason' );
insert into actors_actresses values (	'X00013', 'Jessie Royce Landis' );
insert into actors_actresses values (	'Y00048', 'Kevin Spacey' );
insert into actors_actresses values (	'Y00049', 'Russell Crowe' );
insert into actors_actresses values (	'Y00050', 'Guy Pearce (II)');
insert into actors_actresses values (	'Y00051', 'James Cromwell' );
insert into actors_actresses values (	'Y00052', 'Anthony Perkins');
insert into actors_actresses values (	'X00014', 'Vera Miles' );
insert into actors_actresses values (	'Y00053', 'John Gavin (I)' );
insert into actors_actresses values (	'Y00054', 'Martin Balsam' );
insert into actors_actresses values (	'Y00055', 'Jodie Foster' );
insert into actors_actresses values (	'Y00056', 'Lawrence A. Bonney');
insert into actors_actresses values (	'X00015', 'Kasi Lemmons' );
insert into actors_actresses values (	'Y00057', 'Lawrence T. Wrentz' );
insert into actors_actresses values (	'Y00058', 'Gregory Peck' );
insert into actors_actresses values (	'Y00059', 'John Megna' );
insert into actors_actresses values (	'Y00060', 'Frank Overton' );
insert into actors_actresses values (	'X00016', 'Rosemary Murphy' );
insert into actors_actresses values (	'Y00061', 'James Stewart' );
insert into actors_actresses values (	'X00017', 'Kim Novak' );
insert into actors_actresses values (	'X00018', 'Barbara Bel Geddes' );
insert into actors_actresses values (	'Y00062', 'Tom Helmore' );
insert into actors_actresses values (	'X00019', 'Diahnne Abbott' );
insert into actors_actresses values (	'Y00063', 'Frank Adu' );
insert into actors_actresses values (	'Y00064', 'Victor Argo' );
insert into actors_actresses values (	'Y00065', 'Gino Ardito');
insert into actors_actresses values (	'Y00066', 'John Travolta' );
insert into actors_actresses values (	'Y00067', 'Samuel L. Jackson' );
insert into actors_actresses values (	'Y00068', 'Uma Thurman' );
insert into actors_actresses values (	'X00020', 'Laura Lovelace' );
insert into actors_actresses values (	'Y00069', 'Henry Fonda' );
insert into actors_actresses values (	'Y00070', 'Lee J. Cobb' );
insert into actors_actresses values (	'Y00071', 'Ed Begley' );
insert into actors_actresses values (	'X00021', 'E.G. Marshall' );
insert into actors_actresses values (	'Y00072', 'Humphrey Bogart' );
insert into actors_actresses values (	'X00022', 'Mary Astor' );
insert into actors_actresses values (	'X00023', 'Gladys George' );
insert into actors_actresses values (	'Y00073', 'Peter Lorre' );
insert into actors_actresses values (	'Y00074', 'James Stewart' );
insert into actors_actresses values (	'X00024', 'Donna Reed' );
insert into actors_actresses values (	'Y00075', 'Lionel Barrymore' );
insert into actors_actresses values (	'Y00076', 'Thomas Mitchell (I)' );
insert into actors_actresses values (	'Y00077', 'Peter OToole' );
insert into actors_actresses values (	'Y00078', 'Alec Guinness' );
insert into actors_actresses values (	'Y00079', 'Anthony Quinn' );
insert into actors_actresses values (	'Y00080', 'Jack Hawkins' );
insert into actors_actresses values (	'Y00081', 'Robert De Niro' );
insert into actors_actresses values (	'Y00082', 'Ray Liotta' );
insert into actors_actresses values (	'Y00083', 'Joe Pesci' );
insert into actors_actresses values (	'X00025', 'Lorraine Bracco' );
insert into actors_actresses values (	'Y00084', 'Robin Williams' );
insert into actors_actresses values (	'Y00085', 'Matt Damon' );
insert into actors_actresses values (	'Y00086', 'Ben Affleck');
insert into actors_actresses values (	'X00026', 'Minnie Driver' );
insert into actors_actresses values (	'Y00087', 'Jim Carrey' );
insert into actors_actresses values (	'X00027', 'Laura Linney' );
insert into actors_actresses values (	'Y00088', 'Noah Emmerich' );
insert into actors_actresses values (	'Y00089', 'Natascha McElhone' );
insert into actors_actresses values (	'Y00090', 'Robert De Niro');
insert into actors_actresses values (	'X00028', 'Cathy Moriarty' );
insert into actors_actresses values (	'Y00091', 'Joe Pesci');
insert into actors_actresses values (	'Y00092', 'Frank Vincent');
insert into actors_actresses values (	'Y00093', 'Paul Newman' );
insert into actors_actresses values (	'Y00094', 'Robert Redford' );
insert into actors_actresses values (	'Y00095', 'Robert Shaw (I)' );
insert into actors_actresses values (	'Y00096', 'Charles Durning' );
insert into actors_actresses values (	'Y00097', 'Graham Chapman' );
insert into actors_actresses values (	'Y00098', 'John Cleese');
insert into actors_actresses values (	'Y00099', 'Eric Idle');
insert into actors_actresses values (	'Y00100', 'Terry Gilliam');
insert into actors_actresses values (	'Y00101', 'William Holden' );
insert into actors_actresses values (	'Y00102', 'Alec Guinness');
insert into actors_actresses values (	'Y00103', 'Jack Hawkins' );
insert into actors_actresses values (	'Y00104', 'Sessue Hayakawa' );
insert into actors_actresses values (	'Y00105', 'Marlon Brando' );
insert into actors_actresses values (	'Y00106', 'Robert Duvall' );
insert into actors_actresses values (	'Y00107', 'Martin Sheen'	);
insert into actors_actresses values (	'Y00108', 'Frederic Forrest' );
insert into actors_actresses values (	'X00029', 'Judy Garland');
insert into actors_actresses values (	'Y00109', 'Frank Morgan (I)' );
insert into actors_actresses values (	'Y00110', 'Ray Bolger' );
insert into actors_actresses values (	'Y00111', 'Bert Lahr' );
insert into actors_actresses values (	'Y00112', 'Harrison Ford' );
insert into actors_actresses values (	'Y00113', 'Rutger Hauer' );
insert into actors_actresses values (	'Y00114', 'Sean Young' );
insert into actors_actresses values (	'Y00115', 'Edward James Olmos' );
insert into actors_actresses values (	'Y00116', 'Peter Sallis' );
insert into actors_actresses values (	'Y00117', 'Gene Kelly' );
insert into actors_actresses values (	'Y00118', 'Donald OConnor' );
insert into actors_actresses values (	'X00030', 'Debbie Reynolds' );
insert into actors_actresses values (	'Y00119', 'Jean Hagen' );
insert into actors_actresses values (	'Y00120', 'Jack Nicholson' );
insert into actors_actresses values (	'X00031', 'Faye Dunaway' );
insert into actors_actresses values (	'Y00121', 'John Huston');
insert into actors_actresses values (	'Y00122', 'Perry Lopez' );
insert into actors_actresses values (	'Y00123', 'F. Murray Abraham');
insert into actors_actresses values (	'Y00124', 'Tom Hulce');
insert into actors_actresses values (	'X00032', 'Elizabeth Berridge' );
insert into actors_actresses values (	'Y00125', 'Simon Callow' );
insert into actors_actresses values (	'Y00126', 'Joseph Cotten' );
insert into actors_actresses values (	'X00033', 'Alida Valli' );
insert into actors_actresses values (	'Y00127', 'Trevor Howard' );
insert into actors_actresses values (	'Y00128', 'Orson Welles' );
insert into actors_actresses values (	'Y00129', 'Humphrey Bogart' );
insert into actors_actresses values (	'X00034', 'Katharine Hepburn' );
insert into actors_actresses values (	'Y00130', 'Robert Morley (I)' );
insert into actors_actresses values (	'Y00131', 'Peter Bull' );
insert into actors_actresses values (	'Y00132', 'Tom Skerritt' );
insert into actors_actresses values (	'Y00133', 'Sigourney Weaver' );
insert into actors_actresses values (	'Y00134', 'Veronica Cartwright' );
insert into actors_actresses values (	'Y00135', 'Harry Dean Stanton' );
insert into actors_actresses values (	'Y00136', 'Matthew Broderick' );
insert into actors_actresses values (	'Y00137', 'Denzel Washington' );
insert into actors_actresses values (	'Y00138', 'Cary Elwes' );
insert into actors_actresses values (	'Y00139', 'Morgan Freeman');
insert into actors_actresses values (	'Y00140', 'Mark Hamill' );
insert into actors_actresses values (	'Y00141', 'Harrison Ford' );
insert into actors_actresses values (	'X00035', 'Carrie Fisher' );
insert into actors_actresses values (	'Y00142', 'Billy Dee Williams' );
insert into actors_actresses values (	'Y00143', 'Mel Gibson' );
insert into actors_actresses values (	'X00036', 'Sophie Marceau' );
insert into actors_actresses values (	'Y00144', 'Patrick McGoohan' );
insert into actors_actresses values (	'X00037', 'Catherine McCormack' );
insert into actors_actresses values (	'Y00145', 'Takashi Shimura' );
insert into actors_actresses values (	'Y00146', 'Toshirô Mifune' );
insert into actors_actresses values (	'X00038', 'Yoshio Inaba' );
insert into actors_actresses values (	'X00039', 'Seiji Miyaguchi' );
insert into actors_actresses values (	'Y00147', 'Harvey Keitel' );
insert into actors_actresses values (	'Y00148', 'Tim Roth' );
insert into actors_actresses values (	'Y00149', 'Michael Madsen' );
insert into actors_actresses values (	'Y00150', 'Chris Penn' );
insert into actors_actresses values (	'Y00151', 'Cary Elwes' );
insert into actors_actresses values (	'Y00152', 'Mandy Patinkin');
insert into actors_actresses values (	'Y00153', 'Chris Sarandon' );
insert into actors_actresses values (	'Y00154', 'Christopher Guest' );
insert into actors_actresses values (	'Y00155', 'Jürgen Prochnow' );
insert into actors_actresses values (	'Y00156', 'Herbert Grönemeyer' );
insert into actors_actresses values (	'Y00157', 'Klaus Wennemann' );
insert into actors_actresses values (	'Y00158', 'Hubertus Bengsch' );
