CREATE TABLE EMPLOYEES
(
 ELNAME      VARCHAR(15)    NOT NULL,
 EFNAME      VARCHAR(15)    NOT NULL,
 EMINIT      CHAR,
 ESSN        CHAR(9)        NOT NULL,
 EMPNUM      CHAR(4)        NOT NULL,
 ETITLE      VARCHAR(20),
 ESALARY     DECIMAL(10,2),
 EADDRESS    VARCHAR(35),
 EDEPTNUM    INT            NOT NULL,
 EBRANCH     INT            NOT NULL,
PRIMARY KEY (EMPNUM),
UNIQUE (ESSN)
);
