CREATE TABLE LOANS
(
 LNACCTNUM     CHAR(9)        NOT NULL,
 LNBRANCHNUM   INT            NOT NULL,
 LNDATEOPEN    DATE           NOT NULL,
 LNBALANCE     DECIMAL(11,2)  NOT NULL,
 LNINTRATE     DECIMAL(4,2)   NOT NULL,
 LNTYPE        VARCHAR(13)    NOT NULL,
PRIMARY KEY (LNACCTNUM)
);
