INSERT INTO AIRPORT VALUES
(1,
 'New York City Airport',
 'New York City',
 'NY',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(2,
 'Boston Airport',
 'Boston',
 'MA',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(3,
 'Tempa Airport',
 'Tempa',
 'FL',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(4,
 'Green Bay Airport',
 'Green Bay',
 'WI',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(5,
 'Denver Airport',
 'Denver',
 'CO',
 'MST',
 5);

INSERT INTO AIRPORT VALUES
(6,
 'Los Angles Airport',
 'Los Angles',
 'CA',
 'PST',
 2);

INSERT INTO AIRPORT VALUES
(7,
 'Houston Airport',
 'Houston',
 'TX',
 'PST',
 3);

INSERT INTO AIRPORT VALUES
(8,
 'Miami Airport',
 'Miami',
 'FL',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(9,
 'Oakland Airport',
 'Oakland',
 'FL',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(10,
 'Kansas City Airport',
 'Kansas City',
 'KS',
 'MST',
 4);

INSERT INTO AIRPORT VALUES
(11,
 'Pittsburgh Airport',
 'Pittsburgh',
 'PA',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(12,
 'Chicago Airport',
 'Chicago',
 'IL',
 'CST',
 3);

INSERT INTO AIRPORT VALUES
(13,
 'Detroit Airport',
 'Detroit',
 'MI',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(14,
 'Raleigh Airport',
 'Raleigh',
 'NC',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(15,
 'Baltimore Airport',
 'Baltimore',
 'MD',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(16,
 'Dallas Airport',
 'Dallas',
 'TX',
 'PST',
 1);

INSERT INTO AIRPORT VALUES
(17,
 'Cleveland Airport',
 'Cleveland',
 'CT',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(18,
 'Seattle Airport',
 'Seattle',
 'WA',
 'PST',
 1);

INSERT INTO AIRPORT VALUES
(19,
 'Buffalo Airport',
 'Buffalo',
 'NY',
 'EST',
 2);

INSERT INTO AIRPORT VALUES
(20,
 'Salt Lake Airport',
 'Salt Lake',
 'UT',
 'MST',
 2);

INSERT INTO AIRPORT VALUES
(21,
 'Juneau Airport',
 'Juneau',
 'AL',
 'HAT',
 2);

INSERT INTO AIRPORT VALUES
(22,
 'Anchorage Airport',
 'Anchorage',
 'AL',
 'HAT',
 1);

INSERT INTO AIRPORT VALUES
(23,
 'Austin Airport',
 'Austin',
 'TX',
 'PST',
 3);

INSERT INTO AIRPORT VALUES
(24,
 'Atlanta Airport',
 'Atlanta',
 'GA',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(25,
 'Oklahoma City Airport',
 'Oklahoma City',
 'OH',
 'CST',
 1);

INSERT INTO AIRPORT VALUES
(26,
 'Madison Airport',
 'Madison',
 'WI',
 'CST',
 1);

INSERT INTO AIRPORT VALUES
(27,
 'Jacksonville Airport',
 'Jacksonville',
 'FL ',
 'EST',
 4);

INSERT INTO AIRPORT VALUES
(28,
 'Indianapolis Airport',
 'Indianapolis',
 'IN',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(29,
 'San Francisco Airport',
 'San Francisco',
 'CA',
 'PST',
 3);

INSERT INTO AIRPORT VALUES
(30,
 'Cincinnati Airport',
 'Cincinnati',
 'OH',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(31,
 'New Orleans Airport',
 'New Orleans',
 'LA',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(32,
 'San Diego Airport',
 'San Diego',
 'CA',
 'PST',
 5);

INSERT INTO AIRPORT VALUES
(33,
 'St. Louis Airport',
 'St. Louis',
 'MS',
 'CST',
 3);

INSERT INTO AIRPORT VALUES
(34,
 'Philadelphia Airport',
 'Philadelphia',
 'PA',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(35,
 'Portland Airport',
 'Portland',
 'OR',
 'PST',
 5);

INSERT INTO AIRPORT VALUES
(36,
 'Phoenix Airport',
 'Phoenix',
 'AZ',
 'MST',
 2);

INSERT INTO AIRPORT VALUES
(37,
 'Charleston Airport',
 'Charleston',
 'SC',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(38,
 'Milwukee Airport',
 'Milwukee',
 'WI',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(39,
 'Minneapolis Airport',
 'Minneapolis',
 'MN',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(40,
 'San Jose Airport',
 'San Jose',
 'CA',
 'PST',
 4);

INSERT INTO AIRPORT VALUES
(41,
 'Sacramento Airport',
 'Sacramento',
 'CA',
 'PST',
 2);

INSERT INTO AIRPORT VALUES
(42,
 'Lincoln Airport',
 'Lincoln',
 'NE',
 'MST',
 5);

INSERT INTO AIRPORT VALUES
(43,
 'Tacoma Airport',
 'Tacoma',
 'WA',
 'PST',
 3);

INSERT INTO AIRPORT VALUES
(44,
 'Nashville Airport',
 'Nashville',
 'TN',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(45,
 'Nkoxville Airport',
 'Nkoxville',
 'TN',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(46,
 'San Antonio Airport',
 'San Antonio',
 'TX',
 'PST',
 1);

INSERT INTO AIRPORT VALUES
(47,
 'Norfolk Airport',
 'Norfolk',
 'VA',
 'EST',
 2);

INSERT INTO AIRPORT VALUES
(48,
 'Richmond Airport',
 'Richmond',
 'VA',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(49,
 'Orlando Airport',
 'Orlando',
 'FL',
 'EST',
 2);

INSERT INTO AIRPORT VALUES
(50,
 'Boulder Airport',
 'Boulder',
 'CO',
 'MST',
 3);

INSERT INTO AIRPORT VALUES
(51,
 'Lansing Airport',
 'Lansing',
 'MI',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(52,
 'Ann Arbor Airport',
 'Ann Arbor',
 'MI',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(53,
 'Brooklyn Airport',
 'Brooklyn',
 'NY',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(54,
 'Tallahassee Airport',
 'Tallahassee',
 'FL',
 'EST',
 4);

INSERT INTO AIRPORT VALUES
(55,
 'Albany Airport',
 'Albany',
 'NY',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(56,
 'Columbus Airport',
 'Columbus',
 'OH',
 'CST',
 1);

INSERT INTO AIRPORT VALUES
(57,
 'Dayton Airport',
 'Dayton',
 'OH',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(58,
 'Toledo Airport',
 'Toledo',
 'OH',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(59,
 'Memphis Airport',
 'Memphis',
 'TN',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(60,
 'Reading Airport',
 'Reading',
 'PA',
 'EST',
 3);

INSERT INTO AIRPORT VALUES
(61,
 'Hershey Airport',
 'Hershey',
 'PA',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(62,
 'Syracuse Airport',
 'Syracuse',
 'NY',
 'EST',
 5);

INSERT INTO AIRPORT VALUES
(63,
 'SpringField Airport',
 'SpringField',
 'MO',
 'MST',
 1);

INSERT INTO AIRPORT VALUES
(64,
 'Waco Airport',
 'Waco',
 'TX',
 'PST',
 4);

INSERT INTO AIRPORT VALUES
(65,
 'Cairo Airport',
 'Cairo',
 'IL',
 'CST',
 2);

INSERT INTO AIRPORT VALUES
(66,
 'Athens Airport',
 'Athens',
 'GA',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(67,
 'Macon Airport',
 'Macon',
 'GA',
 'EST',
 4);

INSERT INTO AIRPORT VALUES
(68,
 'Lexington Airport',
 'Lexington',
 'KY',
 'CST',
 3);

INSERT INTO AIRPORT VALUES
(69,
 'Flint Airport',
 'Flint',
 'MI',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(70,
 'Atlantic City Airport',
 'Atlantic City',
 'NJ',
 'EST',
 2);

INSERT INTO AIRPORT VALUES
(71,
 'Jersey City Airport',
 'Jersey City',
 'NJ',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(72,
 'Trenton Airport',
 'Trenton',
 'NJ',
 'EST',
 2);

INSERT INTO AIRPORT VALUES
(73,
 'Tacoma Airport',
 'Tacoma',
 'WA',
 'PST',
 1);

INSERT INTO AIRPORT VALUES
(74,
 'Worcester Airport',
 'Worcester',
 'MA',
 'EST',
 1);

INSERT INTO AIRPORT VALUES
(75,
 'Frankfort Airport',
 'Frankfort',
 'KY',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(76,
 'Rochester Airport',
 'Rochester',
 'MN',
 'CST',
 3);

INSERT INTO AIRPORT VALUES
(77,
 'St. Paul Airport',
 'St. Paul',
 'MN',
 'CST',
 5);

INSERT INTO AIRPORT VALUES
(78,
 'Burbank Airport',
 'Burbank',
 'CA',
 'PST',
 2);

INSERT INTO AIRPORT VALUES
(79,
 'Tulsa Airport',
 'Tulsa',
 'OK',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(80,
 'Dayton Airport',
 'Dayton',
 'OH',
 'CST',
 4);

INSERT INTO AIRPORT VALUES
(81,
 'Durham Airport',
 'Durham',
 'NC',
 'EST',
 4);

