INSERT INTO FLIGHT_LEG VALUES
('TWA198',
 'Philadelphia Airport',
 '03:28',
 'Austin Airport',
 '08:30',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA117',
 'Frankfort Airport',
 '14:28',
 'Macon Airport',
 '17:34',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir132',
 'Albany Airport',
 '03:53',
 'Nashville Airport',
 '06:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA60',
 'Hershey Airport',
 '21:32',
 'Nashville Airport',
 '23:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW148',
 'Madison Airport',
 '03:33',
 'New York City Airport',
 '08:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA88',
 'Oakland Airport',
 '07:49',
 'Portland Airport',
 '09:02',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW273',
 'Cincinnati Airport',
 '14:12',
 'Phoenix Airport',
 '14:12',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir10',
 'Cairo Airport',
 '10:21',
 'Frankfort Airport',
 '10:30',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA262',
 'Los Angles Airport',
 '22:26',
 'Nkoxville Airport',
 '22:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta47',
 'Memphis Airport',
 '14:34',
 'Frankfort Airport',
 '19:34',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA84',
 'Austin Airport',
 '02:08',
 'Atlanta Airport',
 '02:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir217',
 'Minneapolis Airport',
 '18:42',
 'Frankfort Airport',
 '22:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA183',
 'Hershey Airport',
 '04:38',
 'Orlando Airport',
 '05:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW232',
 'Dayton Airport',
 '14:38',
 'Flint Airport',
 '15:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA124',
 'Boston Airport',
 '21:31',
 'Austin Airport',
 '00:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA73',
 'Nashville Airport',
 '23:14',
 'Buffalo Airport',
 '02:25',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW80',
 'Tacoma Airport',
 '02:38',
 'Durham Airport',
 '06:38',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir54',
 'Cairo Airport',
 '14:40',
 'Sacramento Airport',
 '17:49',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta282',
 'San Francisco Airport',
 '06:52',
 'Atlantic City Airport',
 '08:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA141',
 'Syracuse Airport',
 '19:11',
 'Salt Lake Airport',
 '21:19',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA293',
 'Dallas Airport',
 '06:38',
 'Cairo Airport',
 '09:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW232',
 'New York City Airport',
 '08:20',
 'Dayton Airport',
 '08:30',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA2',
 'Seattle Airport',
 '13:49',
 'Juneau Airport',
 '15:59',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA169',
 'Lansing Airport',
 '13:03',
 'Waco Airport',
 '17:06',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA134',
 'SpringField Airport',
 '08:36',
 'Indianapolis Airport',
 '08:44',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA181',
 'Frankfort Airport',
 '23:32',
 'Tempa Airport',
 '04:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW50',
 'Flint Airport',
 '00:00',
 'Tacoma Airport',
 '01:05',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL145',
 'Dayton Airport',
 '05:44',
 'Tacoma Airport',
 '07:45',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA234',
 'Lansing Airport',
 '14:51',
 'Lexington Airport',
 '15:01',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW43',
 'Jacksonville Airport',
 '22:35',
 'Oklahoma City Airport',
 '23:35',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW147',
 'Burbank Airport',
 '05:02',
 'Dayton Airport',
 '08:05',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL113',
 'Indianapolis Airport',
 '13:03',
 'Miami Airport',
 '13:17',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA144',
 'Jacksonville Airport',
 '13:29',
 'Baltimore Airport',
 '16:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA79',
 'Orlando Airport',
 '05:16',
 'San Diego Airport',
 '08:16',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW135',
 'Athens Airport',
 '19:14',
 'Boston Airport',
 '23:22',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir235',
 'Nashville Airport',
 '09:38',
 'Boulder Airport',
 '11:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA80',
 'Tulsa Airport',
 '10:35',
 'Boulder Airport',
 '10:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA0',
 'Norfolk Airport',
 '02:12',
 'San Antonio Airport',
 '04:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA103',
 'Norfolk Airport',
 '23:23',
 'Syracuse Airport',
 '01:23',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta95',
 'Anchorage Airport',
 '07:01',
 'Tempa Airport',
 '12:09',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA222',
 'St. Paul Airport',
 '15:10',
 'Minneapolis Airport',
 '16:13',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir257',
 'Tacoma Airport',
 '19:18',
 'Columbus Airport',
 '21:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA62',
 'Cleveland Airport',
 '16:19',
 'Seattle Airport',
 '18:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA265',
 'Cincinnati Airport',
 '06:45',
 'Miami Airport',
 '07:45',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA266',
 'Dallas Airport',
 '23:45',
 'Worcester Airport',
 '01:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW73',
 'Minneapolis Airport',
 '19:04',
 'Atlanta Airport',
 '20:14',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA266',
 'Raleigh Airport',
 '14:11',
 'Juneau Airport',
 '18:15',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA119',
 'Tacoma Airport',
 '00:34',
 'Columbus Airport',
 '02:35',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW219',
 'Jacksonville Airport',
 '18:37',
 'Oklahoma City Airport',
 '18:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA32',
 'Lansing Airport',
 '02:33',
 'Chicago Airport',
 '05:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA86',
 'Kansas City Airport',
 '07:35',
 'Lansing Airport',
 '07:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA286',
 'Buffalo Airport',
 '18:39',
 'Denver Airport',
 '21:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW46',
 'Atlantic City Airport',
 '20:06',
 'Atlanta Airport',
 '21:09',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir216',
 'Nashville Airport',
 '16:45',
 'St. Paul Airport',
 '19:51',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA33',
 'Seattle Airport',
 '02:32',
 'San Diego Airport',
 '05:39',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA67',
 'San Antonio Airport',
 '14:21',
 'Orlando Airport',
 '16:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA275',
 'Norfolk Airport',
 '14:46',
 'Tempa Airport',
 '17:00',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir283',
 'Hershey Airport',
 '04:08',
 'Juneau Airport',
 '06:11',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir135',
 'Cairo Airport',
 '20:14',
 'Green Bay Airport',
 '22:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW93',
 'Nashville Airport',
 '04:21',
 'Detroit Airport',
 '08:22',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL37',
 'Albany Airport',
 '19:49',
 'Charleston Airport',
 '20:57',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW215',
 'Cleveland Airport',
 '20:06',
 'Oakland Airport',
 '22:13',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir55',
 'Los Angles Airport',
 '07:50',
 'Portland Airport',
 '07:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA138',
 'Jersey City Airport',
 '11:42',
 'SpringField Airport',
 '14:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta71',
 'Seattle Airport',
 '22:26',
 'Flint Airport',
 '23:37',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA293',
 'Reading Airport',
 '00:07',
 'Columbus Airport',
 '03:14',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW68',
 'Dallas Airport',
 '03:37',
 'Denver Airport',
 '08:46',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW178',
 'Los Angles Airport',
 '21:59',
 'Madison Airport',
 '23:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA69',
 'Chicago Airport',
 '06:24',
 'Indianapolis Airport',
 '10:31',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW142',
 'Flint Airport',
 '07:03',
 'Sacramento Airport',
 '08:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA146',
 'Cleveland Airport',
 '15:55',
 'Macon Airport',
 '18:59',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA234',
 'Athens Airport',
 '16:24',
 'Oakland Airport',
 '18:33',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA297',
 'Charleston Airport',
 '18:21',
 'Athens Airport',
 '19:32',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA150',
 'Ann Arbor Airport',
 '17:07',
 'Oklahoma City Airport',
 '21:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW157',
 'Richmond Airport',
 '21:23',
 'Kansas City Airport',
 '00:26',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA129',
 'Tempa Airport',
 '00:28',
 'Indianapolis Airport',
 '04:32',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta277',
 'Raleigh Airport',
 '23:59',
 'Philadelphia Airport',
 '23:01',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA111',
 'Dallas Airport',
 '09:40',
 'Tallahassee Airport',
 '10:54',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir193',
 'Boston Airport',
 '00:50',
 'Tempa Airport',
 '02:01',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW2',
 'Toledo Airport',
 '21:36',
 'Minneapolis Airport',
 '00:45',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA149',
 'Flint Airport',
 '02:33',
 'Nashville Airport',
 '05:40',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL56',
 'Tempa Airport',
 '17:35',
 'Green Bay Airport',
 '17:43',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL124',
 'Boston Airport',
 '07:31',
 'Philadelphia Airport',
 '11:41',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA225',
 'Kansas City Airport',
 '21:56',
 'Indianapolis Airport',
 '00:03',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA132',
 'Tallahassee Airport',
 '09:40',
 'Dallas Airport',
 '10:53',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA11',
 'Charleston Airport',
 '11:07',
 'St. Louis Airport',
 '15:13',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir123',
 'Baltimore Airport',
 '23:04',
 'Tulsa Airport',
 '01:13',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA68',
 'Atlantic City Airport',
 '17:07',
 'Pittsburgh Airport',
 '20:15',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL10',
 'Dayton Airport',
 '04:09',
 'Anchorage Airport',
 '08:12',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW78',
 'Rochester Airport',
 '08:19',
 'St. Louis Airport',
 '13:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA279',
 'Brooklyn Airport',
 '02:25',
 'Macon Airport',
 '02:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA245',
 'Detroit Airport',
 '11:33',
 'Syracuse Airport',
 '14:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA111',
 'SpringField Airport',
 '11:16',
 'Salt Lake Airport',
 '15:21',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA53',
 'Richmond Airport',
 '16:34',
 'Oklahoma City Airport',
 '16:42',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA245',
 'Syracuse Airport',
 '22:40',
 'Anchorage Airport',
 '23:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL4',
 'Detroit Airport',
 '15:20',
 'Madison Airport',
 '18:27',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW38',
 'SpringField Airport',
 '10:01',
 'Frankfort Airport',
 '13:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir97',
 'Flint Airport',
 '16:28',
 'Norfolk Airport',
 '16:42',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW94',
 'Frankfort Airport',
 '07:24',
 'Tempa Airport',
 '08:28',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW53',
 'Macon Airport',
 '18:04',
 'Tallahassee Airport',
 '19:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta190',
 'San Diego Airport',
 '14:45',
 'Burbank Airport',
 '15:54',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW220',
 'Austin Airport',
 '18:01',
 'Tallahassee Airport',
 '19:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW179',
 'Trenton Airport',
 '12:59',
 'Houston Airport',
 '16:03',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL154',
 'San Diego Airport',
 '17:33',
 'Madison Airport',
 '18:41',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta230',
 'Worcester Airport',
 '03:16',
 'Dallas Airport',
 '04:25',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA220',
 'Tulsa Airport',
 '21:55',
 'Sacramento Airport',
 '22:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL57',
 'Indianapolis Airport',
 '19:16',
 'Cincinnati Airport',
 '22:19',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir16',
 'Lansing Airport',
 '07:17',
 'Tacoma Airport',
 '08:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA218',
 'Tallahassee Airport',
 '20:20',
 'Lexington Airport',
 '23:20',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW149',
 'Toledo Airport',
 '04:52',
 'Cleveland Airport',
 '06:59',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA273',
 'Reading Airport',
 '13:42',
 'Pittsburgh Airport',
 '14:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL250',
 'Syracuse Airport',
 '05:37',
 'Waco Airport',
 '09:48',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA99',
 'Oklahoma City Airport',
 '14:36',
 'Tacoma Airport',
 '17:49',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA208',
 'Frankfort Airport',
 '12:18',
 'Charleston Airport',
 '14:20',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA43',
 'Nkoxville Airport',
 '21:04',
 'Austin Airport',
 '00:08',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA18',
 'San Jose Airport',
 '08:51',
 'Cleveland Airport',
 '11:59',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW1',
 'Los Angles Airport',
 '03:03',
 'Albany Airport',
 '06:16',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA215',
 'Dayton Airport',
 '22:36',
 'Durham Airport',
 '01:43',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW115',
 'SpringField Airport',
 '15:37',
 'Dayton Airport',
 '20:49',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW97',
 'Durham Airport',
 '03:53',
 'Miami Airport',
 '07:01',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL169',
 'Orlando Airport',
 '04:05',
 'Lansing Airport',
 '07:11',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL23',
 'Toledo Airport',
 '13:19',
 'Athens Airport',
 '14:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA78',
 'Raleigh Airport',
 '14:11',
 'St. Louis Airport',
 '17:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA63',
 'Tacoma Airport',
 '01:38',
 'Cleveland Airport',
 '03:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL152',
 'Frankfort Airport',
 '08:01',
 'Sacramento Airport',
 '11:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW199',
 'Denver Airport',
 '10:16',
 'Burbank Airport',
 '10:18',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta24',
 'Lexington Airport',
 '03:14',
 'St. Paul Airport',
 '07:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA152',
 'Frankfort Airport',
 '21:34',
 'Macon Airport',
 '22:45',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL136',
 'Lexington Airport',
 '18:42',
 'Atlantic City Airport',
 '20:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA42',
 'Phoenix Airport',
 '21:18',
 'Syracuse Airport',
 '23:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta158',
 'Reading Airport',
 '15:10',
 'Green Bay Airport',
 '18:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA147',
 'Orlando Airport',
 '09:57',
 'Richmond Airport',
 '11:08',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA137',
 'Nkoxville Airport',
 '14:22',
 'Boulder Airport',
 '14:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW262',
 'Salt Lake Airport',
 '15:55',
 'Tallahassee Airport',
 '19:57',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW261',
 'Dayton Airport',
 '11:47',
 'Tacoma Airport',
 '15:49',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA137',
 'Miami Airport',
 '23:09',
 'New York City Airport',
 '02:09',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA29',
 'Burbank Airport',
 '08:13',
 'Lansing Airport',
 '10:26',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW96',
 'Dayton Airport',
 '11:27',
 'Chicago Airport',
 '13:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA200',
 'Toledo Airport',
 '21:26',
 'New York City Airport',
 '21:31',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA105',
 'Boulder Airport',
 '18:50',
 'Cairo Airport',
 '21:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA234',
 'Lexington Airport',
 '03:25',
 'Juneau Airport',
 '07:32',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir190',
 'Hershey Airport',
 '12:14',
 'Cairo Airport',
 '13:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta87',
 'Tulsa Airport',
 '15:23',
 'Nkoxville Airport',
 '17:34',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta288',
 'Portland Airport',
 '20:59',
 'Phoenix Airport',
 '20:13',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA160',
 'San Jose Airport',
 '22:06',
 'Flint Airport',
 '02:06',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA47',
 'Seattle Airport',
 '07:08',
 'Milwukee Airport',
 '11:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA199',
 'Atlantic City Airport',
 '05:01',
 'Los Angles Airport',
 '08:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA0',
 'Denver Airport',
 '06:26',
 'St. Paul Airport',
 '07:37',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir41',
 'Pittsburgh Airport',
 '21:58',
 'Trenton Airport',
 '22:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW126',
 'Salt Lake Airport',
 '09:35',
 'Cleveland Airport',
 '13:38',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA23',
 'Dallas Airport',
 '06:35',
 'Tallahassee Airport',
 '07:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA193',
 'Minneapolis Airport',
 '11:17',
 'Buffalo Airport',
 '15:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir93',
 'Sacramento Airport',
 '13:03',
 'Minneapolis Airport',
 '16:13',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir12',
 'Nashville Airport',
 '01:30',
 'Miami Airport',
 '01:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA249',
 'Columbus Airport',
 '17:12',
 'Frankfort Airport',
 '19:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA288',
 'Charleston Airport',
 '06:18',
 'Burbank Airport',
 '09:30',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta121',
 'Boston Airport',
 '15:34',
 'Orlando Airport',
 '15:48',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW105',
 'Jacksonville Airport',
 '15:20',
 'Lansing Airport',
 '15:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA205',
 'Buffalo Airport',
 '06:32',
 'Durham Airport',
 '09:39',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir67',
 'Austin Airport',
 '08:50',
 'Boston Airport',
 '10:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA117',
 'Sacramento Airport',
 '13:51',
 'San Antonio Airport',
 '13:54',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA234',
 'Reading Airport',
 '16:25',
 'Tallahassee Airport',
 '20:25',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA85',
 'Nashville Airport',
 '19:34',
 'Kansas City Airport',
 '22:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA44',
 'Tacoma Airport',
 '11:45',
 'Lansing Airport',
 '14:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW99',
 'San Francisco Airport',
 '14:25',
 'Lincoln Airport',
 '18:38',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA223',
 'Lincoln Airport',
 '05:43',
 'Raleigh Airport',
 '08:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA185',
 'St. Louis Airport',
 '10:20',
 'Minneapolis Airport',
 '14:24',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL254',
 'Tacoma Airport',
 '13:16',
 'Dayton Airport',
 '17:19',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW80',
 'Lincoln Airport',
 '14:42',
 'Orlando Airport',
 '17:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL182',
 'Houston Airport',
 '20:32',
 'Norfolk Airport',
 '20:34',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL167',
 'Minneapolis Airport',
 '14:27',
 'Jersey City Airport',
 '16:29',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL127',
 'Sacramento Airport',
 '13:08',
 'Seattle Airport',
 '15:15',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA195',
 'Syracuse Airport',
 '01:24',
 'New York City Airport',
 '01:25',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW236',
 'Atlantic City Airport',
 '10:36',
 'Lexington Airport',
 '11:42',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA20',
 'Raleigh Airport',
 '13:53',
 'Indianapolis Airport',
 '14:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA158',
 'Worcester Airport',
 '20:50',
 'St. Louis Airport',
 '20:00',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA217',
 'Lincoln Airport',
 '08:57',
 'Philadelphia Airport',
 '11:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA228',
 'San Antonio Airport',
 '06:07',
 'Lexington Airport',
 '08:08',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA173',
 'San Antonio Airport',
 '13:43',
 'Miami Airport',
 '17:47',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA151',
 'New Orleans Airport',
 '10:33',
 'Lexington Airport',
 '14:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA110',
 'Pittsburgh Airport',
 '16:48',
 'Oklahoma City Airport',
 '20:49',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW262',
 'Nkoxville Airport',
 '15:19',
 'Juneau Airport',
 '17:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA179',
 'Reading Airport',
 '08:53',
 'Pittsburgh Airport',
 '11:57',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta213',
 'Phoenix Airport',
 '21:59',
 'Dayton Airport',
 '01:13',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir37',
 'Baltimore Airport',
 '04:11',
 'Atlanta Airport',
 '05:13',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA203',
 'Ann Arbor Airport',
 '22:33',
 'San Antonio Airport',
 '23:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA219',
 'Seattle Airport',
 '13:13',
 'Cairo Airport',
 '17:18',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL62',
 'Salt Lake Airport',
 '11:44',
 'Houston Airport',
 '11:53',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW129',
 'Nkoxville Airport',
 '13:36',
 'Salt Lake Airport',
 '15:40',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta217',
 'Boulder Airport',
 '22:54',
 'Sacramento Airport',
 '23:55',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW228',
 'Norfolk Airport',
 '14:22',
 'Lansing Airport',
 '16:34',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA229',
 'Minneapolis Airport',
 '09:46',
 'Toledo Airport',
 '13:52',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL222',
 'San Antonio Airport',
 '18:56',
 'Los Angles Airport',
 '21:57',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta93',
 'Tulsa Airport',
 '18:32',
 'Philadelphia Airport',
 '20:44',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA214',
 'Lexington Airport',
 '07:50',
 'Atlanta Airport',
 '07:57',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA75',
 'Memphis Airport',
 '20:55',
 'Toledo Airport',
 '00:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW229',
 'Frankfort Airport',
 '10:15',
 'Minneapolis Airport',
 '14:25',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA94',
 'Norfolk Airport',
 '22:16',
 'Baltimore Airport',
 '22:24',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir292',
 'Madison Airport',
 '03:16',
 'Portland Airport',
 '03:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta258',
 'Boulder Airport',
 '16:56',
 'Trenton Airport',
 '19:01',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA75',
 'Hershey Airport',
 '08:57',
 'Jacksonville Airport',
 '08:59',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW142',
 'Burbank Airport',
 '02:46',
 'Hershey Airport',
 '03:54',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA174',
 'Memphis Airport',
 '18:30',
 'Philadelphia Airport',
 '18:32',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW121',
 'Minneapolis Airport',
 '08:45',
 'Atlanta Airport',
 '09:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA13',
 'Tacoma Airport',
 '00:10',
 'Milwukee Airport',
 '03:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW118',
 'Sacramento Airport',
 '16:44',
 'Baltimore Airport',
 '17:58',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir57',
 'Miami Airport',
 '00:51',
 'Los Angles Airport',
 '01:52',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA81',
 'Durham Airport',
 '07:25',
 'Nashville Airport',
 '11:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW72',
 'Tacoma Airport',
 '02:56',
 'Boston Airport',
 '02:01',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW65',
 'Waco Airport',
 '19:03',
 'Oklahoma City Airport',
 '19:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW19',
 'Columbus Airport',
 '00:45',
 'San Diego Airport',
 '00:58',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW130',
 'San Diego Airport',
 '06:30',
 'Hershey Airport',
 '10:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW225',
 'Macon Airport',
 '05:46',
 'Hershey Airport',
 '05:51',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir117',
 'Juneau Airport',
 '00:44',
 'Richmond Airport',
 '04:57',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta28',
 'Frankfort Airport',
 '15:08',
 'Boulder Airport',
 '17:20',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW69',
 'Richmond Airport',
 '15:27',
 'Cincinnati Airport',
 '16:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL97',
 'Indianapolis Airport',
 '06:13',
 'Norfolk Airport',
 '10:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir251',
 'Macon Airport',
 '02:10',
 'Dayton Airport',
 '06:15',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir264',
 'Oakland Airport',
 '22:01',
 'Dayton Airport',
 '00:04',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA28',
 'Trenton Airport',
 '23:31',
 'San Diego Airport',
 '00:45',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta67',
 'Madison Airport',
 '12:50',
 'Boston Airport',
 '12:56',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA9',
 'Macon Airport',
 '20:14',
 'Cincinnati Airport',
 '22:27',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA177',
 'Raleigh Airport',
 '12:25',
 'Miami Airport',
 '15:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir84',
 'Worcester Airport',
 '09:57',
 'Nashville Airport',
 '11:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir32',
 'Cleveland Airport',
 '04:12',
 'Green Bay Airport',
 '07:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL272',
 'Cincinnati Airport',
 '01:39',
 'Memphis Airport',
 '04:47',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta202',
 'Columbus Airport',
 '23:13',
 'Baltimore Airport',
 '01:26',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA92',
 'Lincoln Airport',
 '21:15',
 'Buffalo Airport',
 '21:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA152',
 'Reading Airport',
 '13:03',
 'Jacksonville Airport',
 '13:16',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta269',
 'Tacoma Airport',
 '12:57',
 'Indianapolis Airport',
 '16:58',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW213',
 'Houston Airport',
 '08:14',
 'Macon Airport',
 '11:23',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA61',
 'Nkoxville Airport',
 '12:44',
 'Tempa Airport',
 '16:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW22',
 'Tallahassee Airport',
 '23:45',
 'Nashville Airport',
 '01:55',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW71',
 'Flint Airport',
 '23:52',
 'Tallahassee Airport',
 '01:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW146',
 'SpringField Airport',
 '21:31',
 'Nashville Airport',
 '00:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW169',
 'Sacramento Airport',
 '14:44',
 'Raleigh Airport',
 '18:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA263',
 'Dayton Airport',
 '13:26',
 'Boulder Airport',
 '14:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA276',
 'Albany Airport',
 '12:20',
 'Columbus Airport',
 '17:33',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA276',
 'Durham Airport',
 '01:28',
 'San Antonio Airport',
 '04:28',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA21',
 'San Jose Airport',
 '20:56',
 'Philadelphia Airport',
 '21:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA237',
 'Kansas City Airport',
 '04:05',
 'Oklahoma City Airport',
 '04:06',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta246',
 'Tempa Airport',
 '12:39',
 'Phoenix Airport',
 '16:51',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL76',
 'Dallas Airport',
 '10:43',
 'Cleveland Airport',
 '12:53',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW134',
 'Albany Airport',
 '02:40',
 'Jacksonville Airport',
 '05:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta218',
 'Portland Airport',
 '11:59',
 'Oakland Airport',
 '14:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW30',
 'San Diego Airport',
 '23:49',
 'Kansas City Airport',
 '02:00',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW192',
 'Boston Airport',
 '01:31',
 'San Francisco Airport',
 '02:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW164',
 'Flint Airport',
 '03:03',
 'Milwukee Airport',
 '06:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW115',
 'Raleigh Airport',
 '09:15',
 'Toledo Airport',
 '09:21',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA84',
 'San Diego Airport',
 '11:29',
 'San Francisco Airport',
 '12:33',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA5',
 'Chicago Airport',
 '00:29',
 'Norfolk Airport',
 '00:32',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA43',
 'Denver Airport',
 '20:20',
 'Jersey City Airport',
 '22:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA88',
 'Flint Airport',
 '17:07',
 'Detroit Airport',
 '18:10',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta182',
 'Richmond Airport',
 '22:51',
 'Oakland Airport',
 '02:58',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL268',
 'Minneapolis Airport',
 '23:03',
 'Ann Arbor Airport',
 '00:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA203',
 'Lincoln Airport',
 '09:53',
 'New York City Airport',
 '11:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA92',
 'Jersey City Airport',
 '20:15',
 'Austin Airport',
 '23:17',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA78',
 'Milwukee Airport',
 '23:01',
 'Tacoma Airport',
 '01:01',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA146',
 'Burbank Airport',
 '03:48',
 'SpringField Airport',
 '04:57',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL58',
 'Flint Airport',
 '16:59',
 'Toledo Airport',
 '20:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW145',
 'Tempa Airport',
 '01:57',
 'St. Louis Airport',
 '01:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA54',
 'Atlanta Airport',
 '23:32',
 'Syracuse Airport',
 '23:44',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA103',
 'Tallahassee Airport',
 '16:09',
 'St. Paul Airport',
 '17:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA182',
 'Nashville Airport',
 '02:12',
 'Nkoxville Airport',
 '02:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA89',
 'Tallahassee Airport',
 '03:20',
 'Baltimore Airport',
 '04:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL42',
 'Lincoln Airport',
 '17:01',
 'Denver Airport',
 '19:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA143',
 'Salt Lake Airport',
 '21:49',
 'Cleveland Airport',
 '23:00',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA143',
 'New Orleans Airport',
 '16:46',
 'Seattle Airport',
 '20:00',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW285',
 'Ann Arbor Airport',
 '07:49',
 'Portland Airport',
 '09:54',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL81',
 'New Orleans Airport',
 '12:18',
 'Orlando Airport',
 '15:29',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir65',
 'Minneapolis Airport',
 '19:47',
 'Trenton Airport',
 '23:51',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA135',
 'Anchorage Airport',
 '04:47',
 'Hershey Airport',
 '06:47',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta73',
 'Flint Airport',
 '04:59',
 'Reading Airport',
 '04:00',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir64',
 'Norfolk Airport',
 '04:30',
 'Charleston Airport',
 '08:41',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta165',
 'Lexington Airport',
 '06:21',
 'SpringField Airport',
 '09:24',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA89',
 'Buffalo Airport',
 '07:02',
 'San Antonio Airport',
 '09:14',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW151',
 'Durham Airport',
 '12:31',
 'Ann Arbor Airport',
 '15:38',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL150',
 'Richmond Airport',
 '14:36',
 'Jacksonville Airport',
 '14:38',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA292',
 'Miami Airport',
 '21:08',
 'Dayton Airport',
 '00:08',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA59',
 'Syracuse Airport',
 '12:09',
 'Burbank Airport',
 '16:16',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL82',
 'Atlantic City Airport',
 '17:27',
 'Portland Airport',
 '21:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA54',
 'Charleston Airport',
 '05:52',
 'Raleigh Airport',
 '06:05',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL95',
 'Rochester Airport',
 '02:26',
 'St. Louis Airport',
 '04:37',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW186',
 'Worcester Airport',
 '20:12',
 'Syracuse Airport',
 '00:13',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL34',
 'Kansas City Airport',
 '10:10',
 'New York City Airport',
 '14:20',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW161',
 'Houston Airport',
 '09:05',
 'Minneapolis Airport',
 '10:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL48',
 'Syracuse Airport',
 '19:45',
 'Albany Airport',
 '19:57',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW290',
 'Toledo Airport',
 '22:11',
 'Orlando Airport',
 '03:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA282',
 'Sacramento Airport',
 '17:00',
 'Albany Airport',
 '21:08',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW24',
 'Milwukee Airport',
 '16:58',
 'Tallahassee Airport',
 '18:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW174',
 'Cincinnati Airport',
 '05:04',
 'Oklahoma City Airport',
 '08:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL65',
 'Oklahoma City Airport',
 '20:57',
 'New York City Airport',
 '23:11',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW65',
 'Memphis Airport',
 '07:34',
 'Tempa Airport',
 '12:40',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW216',
 'Buffalo Airport',
 '12:00',
 'Durham Airport',
 '15:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir255',
 'Nashville Airport',
 '12:24',
 'Memphis Airport',
 '16:38',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW103',
 'Tempa Airport',
 '19:23',
 'Raleigh Airport',
 '23:32',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir33',
 'Oakland Airport',
 '07:26',
 'Madison Airport',
 '07:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA71',
 'Cairo Airport',
 '11:58',
 'Milwukee Airport',
 '15:04',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA95',
 'Tempa Airport',
 '03:35',
 'Tallahassee Airport',
 '07:45',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA226',
 'Phoenix Airport',
 '17:37',
 'Charleston Airport',
 '21:40',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA258',
 'Columbus Airport',
 '04:57',
 'Lincoln Airport',
 '05:10',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA183',
 'Green Bay Airport',
 '01:03',
 'Frankfort Airport',
 '01:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA81',
 'Buffalo Airport',
 '06:24',
 'Anchorage Airport',
 '09:26',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW276',
 'Kansas City Airport',
 '09:08',
 'Charleston Airport',
 '11:14',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta243',
 'Dayton Airport',
 '23:12',
 'Jersey City Airport',
 '01:21',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL159',
 'Tempa Airport',
 '01:15',
 'Nashville Airport',
 '04:25',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA3',
 'Ann Arbor Airport',
 '14:19',
 'Memphis Airport',
 '15:25',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW38',
 'Macon Airport',
 '09:15',
 'Pittsburgh Airport',
 '10:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA89',
 'Cleveland Airport',
 '23:57',
 'Rochester Airport',
 '02:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW67',
 'Miami Airport',
 '03:01',
 'Anchorage Airport',
 '04:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL138',
 'Buffalo Airport',
 '01:54',
 'Brooklyn Airport',
 '02:55',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA258',
 'Toledo Airport',
 '18:47',
 'Detroit Airport',
 '20:55',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA52',
 'Seattle Airport',
 '02:44',
 'San Francisco Airport',
 '06:51',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA224',
 'Nkoxville Airport',
 '07:48',
 'Seattle Airport',
 '08:55',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA175',
 'Albany Airport',
 '14:06',
 'Columbus Airport',
 '14:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL7',
 'Oklahoma City Airport',
 '18:57',
 'Tallahassee Airport',
 '19:11',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA155',
 'Atlanta Airport',
 '21:53',
 'Los Angles Airport',
 '01:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW288',
 'Charleston Airport',
 '19:17',
 'Kansas City Airport',
 '20:18',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW76',
 'Waco Airport',
 '06:32',
 'Nashville Airport',
 '09:45',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA105',
 'Cincinnati Airport',
 '23:07',
 'Houston Airport',
 '00:09',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA261',
 'Trenton Airport',
 '06:01',
 'Macon Airport',
 '08:09',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA159',
 'Atlanta Airport',
 '04:04',
 'Athens Airport',
 '04:07',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA225',
 'Flint Airport',
 '08:18',
 'Salt Lake Airport',
 '12:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW240',
 'Tallahassee Airport',
 '09:41',
 'New York City Airport',
 '10:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW196',
 'St. Louis Airport',
 '15:35',
 'Atlantic City Airport',
 '16:44',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir222',
 'Oakland Airport',
 '12:21',
 'Juneau Airport',
 '14:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW42',
 'Green Bay Airport',
 '01:01',
 'Lexington Airport',
 '03:10',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA210',
 'Jacksonville Airport',
 '01:17',
 'Ann Arbor Airport',
 '04:23',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA190',
 'Juneau Airport',
 '00:10',
 'Minneapolis Airport',
 '02:18',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir29',
 'Philadelphia Airport',
 '01:11',
 'San Jose Airport',
 '02:23',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA239',
 'Hershey Airport',
 '16:35',
 'Anchorage Airport',
 '18:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL89',
 'Burbank Airport',
 '12:25',
 'Chicago Airport',
 '15:31',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW62',
 'Flint Airport',
 '05:18',
 'Lansing Airport',
 '05:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW268',
 'New Orleans Airport',
 '00:20',
 'Boulder Airport',
 '04:30',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL201',
 'Austin Airport',
 '18:16',
 'SpringField Airport',
 '20:24',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW51',
 'Baltimore Airport',
 '17:36',
 'Rochester Airport',
 '18:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW85',
 'Richmond Airport',
 '15:47',
 'Jacksonville Airport',
 '19:51',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta13',
 'Green Bay Airport',
 '22:34',
 'Atlanta Airport',
 '01:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA274',
 'Rochester Airport',
 '08:18',
 'Tallahassee Airport',
 '11:32',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW107',
 'Seattle Airport',
 '01:31',
 'Atlanta Airport',
 '04:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW92',
 'Atlanta Airport',
 '10:26',
 'Lexington Airport',
 '15:32',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA245',
 'Madison Airport',
 '08:29',
 'Lexington Airport',
 '11:32',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA220',
 'Jersey City Airport',
 '09:45',
 'Lincoln Airport',
 '09:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir164',
 'Trenton Airport',
 '16:06',
 'Miami Airport',
 '16:20',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir23',
 'Albany Airport',
 '02:08',
 'Dayton Airport',
 '03:22',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW114',
 'Ann Arbor Airport',
 '18:03',
 'Seattle Airport',
 '21:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA15',
 'Salt Lake Airport',
 '13:54',
 'Lexington Airport',
 '16:54',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA182',
 'Brooklyn Airport',
 '07:09',
 'New York City Airport',
 '11:10',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA264',
 'Dayton Airport',
 '11:25',
 'St. Paul Airport',
 '14:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA202',
 'Columbus Airport',
 '09:37',
 'Brooklyn Airport',
 '12:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL123',
 'Memphis Airport',
 '10:21',
 'Indianapolis Airport',
 '14:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA128',
 'Lansing Airport',
 '05:38',
 'SpringField Airport',
 '09:46',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA253',
 'Kansas City Airport',
 '13:14',
 'Minneapolis Airport',
 '14:25',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA231',
 'Rochester Airport',
 '16:02',
 'Portland Airport',
 '18:05',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA190',
 'Macon Airport',
 '13:18',
 'Green Bay Airport',
 '13:19',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA253',
 'Dayton Airport',
 '00:37',
 'Anchorage Airport',
 '04:39',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL83',
 'Lincoln Airport',
 '00:17',
 'Albany Airport',
 '04:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta124',
 'Oakland Airport',
 '04:19',
 'Boulder Airport',
 '06:22',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA56',
 'Madison Airport',
 '07:14',
 'Rochester Airport',
 '09:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir106',
 'Pittsburgh Airport',
 '14:44',
 'Cincinnati Airport',
 '16:55',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA100',
 'Milwukee Airport',
 '06:33',
 'Norfolk Airport',
 '10:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW60',
 'Cincinnati Airport',
 '16:58',
 'Detroit Airport',
 '16:07',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW23',
 'San Francisco Airport',
 '04:20',
 'Green Bay Airport',
 '04:27',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA240',
 'Los Angles Airport',
 '08:57',
 'Houston Airport',
 '11:02',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL210',
 'New Orleans Airport',
 '20:03',
 'Toledo Airport',
 '00:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta270',
 'Durham Airport',
 '03:36',
 'Houston Airport',
 '03:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA142',
 'Toledo Airport',
 '13:50',
 'Atlantic City Airport',
 '14:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir76',
 'Detroit Airport',
 '13:59',
 'Pittsburgh Airport',
 '15:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir161',
 'Dayton Airport',
 '07:21',
 'Trenton Airport',
 '11:30',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA4',
 'Jersey City Airport',
 '15:53',
 'Atlantic City Airport',
 '15:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta110',
 'Macon Airport',
 '13:22',
 'Lexington Airport',
 '13:34',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA108',
 'Green Bay Airport',
 '08:28',
 'Miami Airport',
 '11:28',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW274',
 'Dallas Airport',
 '02:07',
 'Tulsa Airport',
 '02:16',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA232',
 'Denver Airport',
 '11:05',
 'Chicago Airport',
 '14:12',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir126',
 'Oakland Airport',
 '19:38',
 'Flint Airport',
 '23:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL30',
 'Milwukee Airport',
 '16:00',
 'Indianapolis Airport',
 '18:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA128',
 'Waco Airport',
 '11:36',
 'Charleston Airport',
 '12:47',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA17',
 'Anchorage Airport',
 '22:58',
 'Waco Airport',
 '02:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA85',
 'Jersey City Airport',
 '07:50',
 'San Jose Airport',
 '10:51',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir77',
 'Ann Arbor Airport',
 '20:01',
 'Indianapolis Airport',
 '20:09',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta125',
 'Minneapolis Airport',
 '09:06',
 'Kansas City Airport',
 '11:19',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta3',
 'Cairo Airport',
 '12:06',
 'Pittsburgh Airport',
 '12:06',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta66',
 'Minneapolis Airport',
 '17:35',
 'SpringField Airport',
 '20:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL282',
 'Lincoln Airport',
 '16:55',
 'St. Louis Airport',
 '18:08',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA199',
 'Los Angles Airport',
 '12:49',
 'Anchorage Airport',
 '13:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW124',
 'Tulsa Airport',
 '03:03',
 'Tacoma Airport',
 '05:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW96',
 'Baltimore Airport',
 '18:53',
 'San Jose Airport',
 '22:06',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA35',
 'Salt Lake Airport',
 '15:24',
 'Jacksonville Airport',
 '18:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir206',
 'Seattle Airport',
 '19:31',
 'Anchorage Airport',
 '00:32',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir60',
 'Durham Airport',
 '18:36',
 'Minneapolis Airport',
 '18:43',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL246',
 'Burbank Airport',
 '18:58',
 'Athens Airport',
 '18:02',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA156',
 'Charleston Airport',
 '19:25',
 'Trenton Airport',
 '22:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA124',
 'Buffalo Airport',
 '19:06',
 'Memphis Airport',
 '23:13',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL247',
 'Lansing Airport',
 '14:10',
 'Reading Airport',
 '18:18',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA250',
 'Flint Airport',
 '08:32',
 'Salt Lake Airport',
 '09:46',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA222',
 'Tacoma Airport',
 '17:29',
 'Syracuse Airport',
 '21:32',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA209',
 'Charleston Airport',
 '10:54',
 'Indianapolis Airport',
 '12:07',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW182',
 'Oklahoma City Airport',
 '17:51',
 'Anchorage Airport',
 '18:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA166',
 'Boulder Airport',
 '08:08',
 'Kansas City Airport',
 '12:13',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA107',
 'Nkoxville Airport',
 '13:21',
 'Nashville Airport',
 '14:32',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta273',
 'Lexington Airport',
 '13:52',
 'Durham Airport',
 '16:59',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW235',
 'Portland Airport',
 '01:39',
 'Charleston Airport',
 '01:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA157',
 'San Antonio Airport',
 '23:12',
 'Norfolk Airport',
 '03:16',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA190',
 'Oklahoma City Airport',
 '13:12',
 'Reading Airport',
 '17:17',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir22',
 'Columbus Airport',
 '09:34',
 'Salt Lake Airport',
 '11:37',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA70',
 'Cairo Airport',
 '19:28',
 'Orlando Airport',
 '23:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW256',
 'St. Paul Airport',
 '04:38',
 'New Orleans Airport',
 '09:42',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA204',
 'Phoenix Airport',
 '02:25',
 'Philadelphia Airport',
 '04:25',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA33',
 'Detroit Airport',
 '11:56',
 'Phoenix Airport',
 '11:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta223',
 'Ann Arbor Airport',
 '08:21',
 'Los Angles Airport',
 '13:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta106',
 'Norfolk Airport',
 '11:16',
 'Miami Airport',
 '13:20',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL172',
 'Ann Arbor Airport',
 '06:30',
 'Columbus Airport',
 '09:36',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA95',
 'Jacksonville Airport',
 '11:39',
 'New York City Airport',
 '15:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir109',
 'Atlantic City Airport',
 '16:30',
 'Norfolk Airport',
 '18:42',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA21',
 'Hershey Airport',
 '06:12',
 'Pittsburgh Airport',
 '08:16',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA257',
 'Albany Airport',
 '17:04',
 'Syracuse Airport',
 '17:09',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL133',
 'New Orleans Airport',
 '07:06',
 'Milwukee Airport',
 '10:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta62',
 'Sacramento Airport',
 '23:07',
 'Tacoma Airport',
 '01:10',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW0',
 'Atlanta Airport',
 '15:22',
 'Macon Airport',
 '19:36',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA105',
 'Dallas Airport',
 '02:59',
 'Athens Airport',
 '05:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA298',
 'Indianapolis Airport',
 '19:14',
 'Sacramento Airport',
 '22:27',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA121',
 'Hershey Airport',
 '13:34',
 'Philadelphia Airport',
 '13:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW251',
 'St. Louis Airport',
 '03:46',
 'Raleigh Airport',
 '03:00',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta68',
 'Macon Airport',
 '14:09',
 'Orlando Airport',
 '18:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA244',
 'Tacoma Airport',
 '20:03',
 'Kansas City Airport',
 '20:07',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL64',
 'St. Louis Airport',
 '00:18',
 'Dayton Airport',
 '02:19',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir86',
 'Cairo Airport',
 '05:13',
 'San Jose Airport',
 '08:16',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW252',
 'Minneapolis Airport',
 '01:47',
 'San Francisco Airport',
 '06:47',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW34',
 'Tacoma Airport',
 '03:53',
 'Buffalo Airport',
 '06:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL130',
 'Macon Airport',
 '07:44',
 'Columbus Airport',
 '07:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL119',
 'Dallas Airport',
 '01:23',
 'Phoenix Airport',
 '03:29',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW254',
 'Rochester Airport',
 '03:59',
 'Juneau Airport',
 '04:10',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA123',
 'Nashville Airport',
 '04:14',
 'Los Angles Airport',
 '06:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta235',
 'Green Bay Airport',
 '00:21',
 'Denver Airport',
 '04:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir178',
 'Lansing Airport',
 '19:48',
 'Atlantic City Airport',
 '20:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA61',
 'Memphis Airport',
 '01:05',
 'Toledo Airport',
 '04:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA132',
 'Durham Airport',
 '14:28',
 'Sacramento Airport',
 '16:40',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA26',
 'St. Louis Airport',
 '18:30',
 'Anchorage Airport',
 '19:42',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW91',
 'Sacramento Airport',
 '12:12',
 'Phoenix Airport',
 '12:16',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW31',
 'Milwukee Airport',
 '23:27',
 'Lincoln Airport',
 '03:41',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta86',
 'Miami Airport',
 '10:02',
 'Lexington Airport',
 '14:05',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir115',
 'Phoenix Airport',
 '14:20',
 'Detroit Airport',
 '15:33',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta249',
 'Syracuse Airport',
 '09:52',
 'Madison Airport',
 '11:52',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL181',
 'Cleveland Airport',
 '22:45',
 'Durham Airport',
 '22:49',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA46',
 'Nkoxville Airport',
 '14:02',
 'Philadelphia Airport',
 '17:13',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW46',
 'Norfolk Airport',
 '03:50',
 'Trenton Airport',
 '03:03',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL270',
 'Madison Airport',
 '06:05',
 'Macon Airport',
 '09:11',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW176',
 'Macon Airport',
 '16:27',
 'Waco Airport',
 '20:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW112',
 'Dallas Airport',
 '22:13',
 'Tacoma Airport',
 '02:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir252',
 'Sacramento Airport',
 '05:12',
 'Syracuse Airport',
 '06:23',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA254',
 'St. Louis Airport',
 '21:20',
 'Boston Airport',
 '23:22',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW188',
 'Seattle Airport',
 '06:24',
 'Waco Airport',
 '07:26',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA290',
 'Atlantic City Airport',
 '11:43',
 'Tallahassee Airport',
 '12:53',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA98',
 'Tulsa Airport',
 '23:21',
 'Milwukee Airport',
 '23:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA145',
 'St. Louis Airport',
 '11:51',
 'Baltimore Airport',
 '13:52',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW297',
 'Toledo Airport',
 '22:29',
 'Los Angles Airport',
 '03:36',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir212',
 'Frankfort Airport',
 '02:26',
 'St. Louis Airport',
 '02:37',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA9',
 'Lincoln Airport',
 '10:23',
 'Oakland Airport',
 '11:34',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta113',
 'Memphis Airport',
 '21:11',
 'Charleston Airport',
 '01:25',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA145',
 'Kansas City Airport',
 '04:39',
 'Los Angles Airport',
 '04:51',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir148',
 'Juneau Airport',
 '06:11',
 'Milwukee Airport',
 '07:25',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir170',
 'Worcester Airport',
 '19:49',
 'Los Angles Airport',
 '19:57',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA83',
 'Durham Airport',
 '00:57',
 'Jersey City Airport',
 '04:58',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL199',
 'Miami Airport',
 '13:14',
 'Raleigh Airport',
 '16:19',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA112',
 'Tempa Airport',
 '18:09',
 'Detroit Airport',
 '19:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW249',
 'Durham Airport',
 '10:33',
 'Tacoma Airport',
 '10:40',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta148',
 'Green Bay Airport',
 '09:07',
 'San Antonio Airport',
 '09:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA10',
 'Indianapolis Airport',
 '09:50',
 'Austin Airport',
 '09:50',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA243',
 'Richmond Airport',
 '07:54',
 'Albany Airport',
 '11:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW134',
 'Cairo Airport',
 '18:47',
 'Oakland Airport',
 '19:51',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA136',
 'Lansing Airport',
 '15:29',
 'Portland Airport',
 '16:33',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta76',
 'Columbus Airport',
 '00:31',
 'Jersey City Airport',
 '04:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA204',
 'Memphis Airport',
 '11:18',
 'Oakland Airport',
 '11:23',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA113',
 'Boulder Airport',
 '17:37',
 'Frankfort Airport',
 '22:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA38',
 'Nkoxville Airport',
 '14:28',
 'Rochester Airport',
 '14:41',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW95',
 'San Antonio Airport',
 '22:51',
 'Los Angles Airport',
 '00:01',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL140',
 'Phoenix Airport',
 '17:02',
 'Dayton Airport',
 '20:15',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA200',
 'Rochester Airport',
 '19:51',
 'Burbank Airport',
 '21:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA118',
 'Atlantic City Airport',
 '13:25',
 'St. Louis Airport',
 '16:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA28',
 'San Jose Airport',
 '22:01',
 'Waco Airport',
 '22:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW121',
 'Minneapolis Airport',
 '07:00',
 'Dallas Airport',
 '07:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA73',
 'Reading Airport',
 '08:46',
 'San Jose Airport',
 '09:59',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA214',
 'Milwukee Airport',
 '17:31',
 'Nashville Airport',
 '19:43',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA36',
 'Ann Arbor Airport',
 '05:36',
 'Tempa Airport',
 '05:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA276',
 'Worcester Airport',
 '05:59',
 'Phoenix Airport',
 '08:08',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir200',
 'Sacramento Airport',
 '07:39',
 'Lexington Airport',
 '10:44',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta296',
 'San Jose Airport',
 '20:37',
 'Cincinnati Airport',
 '23:51',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA292',
 'Lexington Airport',
 '00:12',
 'Ann Arbor Airport',
 '02:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta116',
 'Baltimore Airport',
 '02:10',
 'Tulsa Airport',
 '07:21',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA284',
 'Green Bay Airport',
 '09:30',
 'Syracuse Airport',
 '13:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW164',
 'Durham Airport',
 '16:32',
 'Austin Airport',
 '20:38',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA19',
 'Lincoln Airport',
 '18:26',
 'Norfolk Airport',
 '21:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA42',
 'Milwukee Airport',
 '17:55',
 'Jacksonville Airport',
 '17:02',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA49',
 'Lansing Airport',
 '00:10',
 'Hershey Airport',
 '04:19',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA198',
 'Dayton Airport',
 '07:20',
 'Durham Airport',
 '10:27',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA264',
 'Rochester Airport',
 '17:32',
 'Houston Airport',
 '19:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA196',
 'Boulder Airport',
 '08:24',
 'Dayton Airport',
 '08:37',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA243',
 'St. Louis Airport',
 '15:53',
 'St. Paul Airport',
 '20:53',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA120',
 'Pittsburgh Airport',
 '02:47',
 'Cleveland Airport',
 '05:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir20',
 'Philadelphia Airport',
 '02:35',
 'Jacksonville Airport',
 '03:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA138',
 'Macon Airport',
 '19:03',
 'Columbus Airport',
 '20:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW219',
 'Dayton Airport',
 '06:46',
 'Flint Airport',
 '08:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW255',
 'Albany Airport',
 '08:53',
 'San Diego Airport',
 '08:00',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW166',
 'Lansing Airport',
 '03:06',
 'Seattle Airport',
 '03:11',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW28',
 'Cleveland Airport',
 '05:07',
 'Athens Airport',
 '07:09',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir224',
 'St. Louis Airport',
 '14:14',
 'Trenton Airport',
 '16:26',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta255',
 'Oklahoma City Airport',
 '20:43',
 'St. Louis Airport',
 '23:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL115',
 'SpringField Airport',
 '02:02',
 'Miami Airport',
 '05:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW13',
 'Tacoma Airport',
 '00:47',
 'Lincoln Airport',
 '03:50',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA284',
 'Rochester Airport',
 '17:29',
 'Anchorage Airport',
 '22:40',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta94',
 'Dayton Airport',
 '00:47',
 'Durham Airport',
 '01:57',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW184',
 'Lansing Airport',
 '11:28',
 'Tacoma Airport',
 '14:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA108',
 'Boston Airport',
 '16:32',
 'Brooklyn Airport',
 '20:41',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW280',
 'Green Bay Airport',
 '03:45',
 'Waco Airport',
 '07:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta0',
 'Nashville Airport',
 '17:49',
 'Lincoln Airport',
 '21:01',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA13',
 'Oakland Airport',
 '23:51',
 'Nashville Airport',
 '01:51',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA227',
 'Lincoln Airport',
 '03:57',
 'San Francisco Airport',
 '04:02',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA50',
 'Rochester Airport',
 '18:42',
 'Lincoln Airport',
 '19:51',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA115',
 'San Francisco Airport',
 '01:38',
 'San Diego Airport',
 '03:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL153',
 'Buffalo Airport',
 '22:03',
 'Milwukee Airport',
 '01:08',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta274',
 'Albany Airport',
 '14:39',
 'Sacramento Airport',
 '17:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL6',
 'Trenton Airport',
 '06:10',
 'Lansing Airport',
 '09:15',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL117',
 'Seattle Airport',
 '09:36',
 'Cairo Airport',
 '10:48',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta40',
 'Oklahoma City Airport',
 '01:40',
 'Durham Airport',
 '03:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW275',
 'Durham Airport',
 '23:22',
 'Nashville Airport',
 '01:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL90',
 'Cairo Airport',
 '05:57',
 'Sacramento Airport',
 '09:00',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW180',
 'Nkoxville Airport',
 '10:26',
 'Baltimore Airport',
 '14:40',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta45',
 'Hershey Airport',
 '11:19',
 'Denver Airport',
 '15:28',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA203',
 'Miami Airport',
 '22:52',
 'New York City Airport',
 '00:03',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW189',
 'Nashville Airport',
 '10:16',
 'Salt Lake Airport',
 '14:25',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA177',
 'Dayton Airport',
 '21:06',
 'Indianapolis Airport',
 '00:19',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta43',
 'New Orleans Airport',
 '08:35',
 'Pittsburgh Airport',
 '08:37',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir271',
 'Miami Airport',
 '01:13',
 'Lexington Airport',
 '04:27',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA263',
 'Houston Airport',
 '08:43',
 'Dayton Airport',
 '08:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL184',
 'Raleigh Airport',
 '20:23',
 'SpringField Airport',
 '20:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW129',
 'San Antonio Airport',
 '16:13',
 'Tallahassee Airport',
 '17:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta55',
 'Austin Airport',
 '04:43',
 'Indianapolis Airport',
 '07:57',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW187',
 'Tempa Airport',
 '09:58',
 'Rochester Airport',
 '10:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA67',
 'Los Angles Airport',
 '08:27',
 'San Diego Airport',
 '11:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA278',
 'Phoenix Airport',
 '09:13',
 'Cairo Airport',
 '13:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA202',
 'Boston Airport',
 '13:16',
 'Worcester Airport',
 '14:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA281',
 'Waco Airport',
 '23:14',
 'Syracuse Airport',
 '23:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA211',
 'Tacoma Airport',
 '13:25',
 'Anchorage Airport',
 '15:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW120',
 'Cairo Airport',
 '11:19',
 'Chicago Airport',
 '13:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta156',
 'Pittsburgh Airport',
 '16:09',
 'San Antonio Airport',
 '19:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW227',
 'Minneapolis Airport',
 '11:57',
 'Philadelphia Airport',
 '12:07',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL170',
 'Milwukee Airport',
 '13:02',
 'St. Paul Airport',
 '16:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW210',
 'Frankfort Airport',
 '03:17',
 'Burbank Airport',
 '05:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA197',
 'Cincinnati Airport',
 '04:58',
 'Waco Airport',
 '07:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA27',
 'Albany Airport',
 '02:51',
 'Durham Airport',
 '06:53',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir104',
 'Oklahoma City Airport',
 '23:12',
 'Rochester Airport',
 '02:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir112',
 'Norfolk Airport',
 '09:12',
 'Boulder Airport',
 '13:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA199',
 'Dayton Airport',
 '11:19',
 'Nashville Airport',
 '14:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA29',
 'Lexington Airport',
 '16:28',
 'Oklahoma City Airport',
 '19:34',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW63',
 'Durham Airport',
 '23:49',
 'Indianapolis Airport',
 '23:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA244',
 'Kansas City Airport',
 '01:13',
 'Denver Airport',
 '01:18',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW214',
 'Buffalo Airport',
 '02:27',
 'Toledo Airport',
 '07:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA150',
 'Columbus Airport',
 '05:46',
 'Frankfort Airport',
 '06:55',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL285',
 'Salt Lake Airport',
 '05:51',
 'Milwukee Airport',
 '09:00',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA45',
 'Atlanta Airport',
 '06:13',
 'Raleigh Airport',
 '10:17',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW26',
 'San Francisco Airport',
 '23:32',
 'St. Paul Airport',
 '00:32',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA281',
 'Miami Airport',
 '18:22',
 'Minneapolis Airport',
 '22:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta151',
 'Ann Arbor Airport',
 '14:18',
 'New York City Airport',
 '17:29',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir137',
 'St. Louis Airport',
 '07:21',
 'Columbus Airport',
 '11:27',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA16',
 'Kansas City Airport',
 '23:37',
 'Buffalo Airport',
 '02:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA193',
 'Dallas Airport',
 '00:05',
 'Indianapolis Airport',
 '02:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA277',
 'San Francisco Airport',
 '18:37',
 'Boston Airport',
 '18:51',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA145',
 'SpringField Airport',
 '11:40',
 'Indianapolis Airport',
 '12:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL191',
 'Burbank Airport',
 '10:54',
 'Atlantic City Airport',
 '12:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW136',
 'Dallas Airport',
 '08:26',
 'Durham Airport',
 '08:39',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW132',
 'Milwukee Airport',
 '09:49',
 'Nashville Airport',
 '10:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW284',
 'Buffalo Airport',
 '21:54',
 'Atlantic City Airport',
 '22:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA22',
 'Hershey Airport',
 '06:25',
 'Phoenix Airport',
 '10:33',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW89',
 'Jersey City Airport',
 '18:27',
 'Columbus Airport',
 '22:30',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA258',
 'Oakland Airport',
 '23:34',
 'Richmond Airport',
 '00:36',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta134',
 'Memphis Airport',
 '08:22',
 'Minneapolis Airport',
 '10:28',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA183',
 'Raleigh Airport',
 '13:10',
 'Boston Airport',
 '16:17',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir180',
 'Hershey Airport',
 '08:23',
 'Miami Airport',
 '10:36',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA74',
 'Milwukee Airport',
 '05:52',
 'San Antonio Airport',
 '07:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW289',
 'Atlanta Airport',
 '03:42',
 'Raleigh Airport',
 '05:50',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW122',
 'Brooklyn Airport',
 '21:13',
 'St. Louis Airport',
 '01:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA135',
 'Athens Airport',
 '17:27',
 'Flint Airport',
 '17:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW169',
 'Jersey City Airport',
 '21:40',
 'Lincoln Airport',
 '01:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW7',
 'Atlantic City Airport',
 '04:37',
 'Denver Airport',
 '05:49',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta154',
 'Raleigh Airport',
 '17:57',
 'Tempa Airport',
 '21:11',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA242',
 'Worcester Airport',
 '19:25',
 'Anchorage Airport',
 '23:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW274',
 'Memphis Airport',
 '20:53',
 'Portland Airport',
 '23:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta44',
 'Jacksonville Airport',
 '07:18',
 'St. Louis Airport',
 '08:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta34',
 'Tallahassee Airport',
 '09:10',
 'Seattle Airport',
 '09:12',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA137',
 'Indianapolis Airport',
 '19:26',
 'Madison Airport',
 '22:27',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL217',
 'Brooklyn Airport',
 '05:37',
 'Columbus Airport',
 '05:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta225',
 'Oakland Airport',
 '00:05',
 'Buffalo Airport',
 '00:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta209',
 'St. Louis Airport',
 '22:28',
 'Phoenix Airport',
 '02:33',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL193',
 'Houston Airport',
 '04:07',
 'Dayton Airport',
 '06:18',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW75',
 'Brooklyn Airport',
 '02:06',
 'San Francisco Airport',
 '05:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA140',
 'Atlantic City Airport',
 '14:21',
 'Minneapolis Airport',
 '14:27',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW242',
 'New York City Airport',
 '17:44',
 'Austin Airport',
 '21:53',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA7',
 'Portland Airport',
 '03:38',
 'San Diego Airport',
 '05:44',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA270',
 'Charleston Airport',
 '14:24',
 'San Antonio Airport',
 '15:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA32',
 'SpringField Airport',
 '14:49',
 'Lincoln Airport',
 '15:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA22',
 'Jacksonville Airport',
 '10:11',
 'Indianapolis Airport',
 '12:23',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW195',
 'Boston Airport',
 '06:18',
 'Denver Airport',
 '08:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA77',
 'Worcester Airport',
 '01:39',
 'Reading Airport',
 '06:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA240',
 'Cairo Airport',
 '06:37',
 'Ann Arbor Airport',
 '07:45',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta259',
 'Madison Airport',
 '01:13',
 'Toledo Airport',
 '05:20',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA164',
 'Minneapolis Airport',
 '14:09',
 'Toledo Airport',
 '17:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA162',
 'Brooklyn Airport',
 '21:24',
 'Jacksonville Airport',
 '23:34',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA84',
 'San Jose Airport',
 '15:28',
 'Minneapolis Airport',
 '18:40',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir173',
 'New Orleans Airport',
 '05:40',
 'Tulsa Airport',
 '07:50',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW216',
 'Tacoma Airport',
 '00:12',
 'Athens Airport',
 '03:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta38',
 'Toledo Airport',
 '13:36',
 'Burbank Airport',
 '18:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA4',
 'San Francisco Airport',
 '17:58',
 'New Orleans Airport',
 '17:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta22',
 'Jersey City Airport',
 '14:36',
 'Worcester Airport',
 '17:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW218',
 'Nashville Airport',
 '12:06',
 'Oklahoma City Airport',
 '15:06',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA51',
 'Oakland Airport',
 '12:26',
 'Buffalo Airport',
 '14:30',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta195',
 'Tacoma Airport',
 '13:11',
 'Ann Arbor Airport',
 '15:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir9',
 'St. Louis Airport',
 '20:47',
 'Seattle Airport',
 '21:58',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA55',
 'Tulsa Airport',
 '06:15',
 'Green Bay Airport',
 '09:22',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA254',
 'Pittsburgh Airport',
 '11:55',
 'Charleston Airport',
 '13:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA205',
 'Waco Airport',
 '05:56',
 'Atlantic City Airport',
 '08:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir228',
 'Lansing Airport',
 '03:28',
 'Athens Airport',
 '05:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA206',
 'New York City Airport',
 '12:09',
 'Tulsa Airport',
 '16:20',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW201',
 'Jacksonville Airport',
 '04:43',
 'San Diego Airport',
 '06:51',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA57',
 'Baltimore Airport',
 '10:36',
 'Burbank Airport',
 '11:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta56',
 'Dayton Airport',
 '05:00',
 'San Jose Airport',
 '10:00',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir154',
 'Indianapolis Airport',
 '18:47',
 'San Antonio Airport',
 '22:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA188',
 'Cleveland Airport',
 '20:30',
 'Detroit Airport',
 '23:32',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir258',
 'Dayton Airport',
 '02:21',
 'Atlanta Airport',
 '05:32',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir192',
 'Denver Airport',
 '15:30',
 'Waco Airport',
 '16:40',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta200',
 'Raleigh Airport',
 '00:00',
 'Detroit Airport',
 '01:08',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL141',
 'Frankfort Airport',
 '16:36',
 'Indianapolis Airport',
 '18:43',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA246',
 'Jersey City Airport',
 '19:18',
 'Lexington Airport',
 '20:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW138',
 'Nashville Airport',
 '04:46',
 'Nkoxville Airport',
 '04:46',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA149',
 'Richmond Airport',
 '00:30',
 'Orlando Airport',
 '02:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA20',
 'Tacoma Airport',
 '19:21',
 'San Diego Airport',
 '21:33',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL276',
 'Baltimore Airport',
 '10:56',
 'Memphis Airport',
 '12:57',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL155',
 'Burbank Airport',
 '08:46',
 'Dayton Airport',
 '09:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir204',
 'Tempa Airport',
 '17:57',
 'Austin Airport',
 '20:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir169',
 'Baltimore Airport',
 '02:55',
 'Portland Airport',
 '04:08',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL147',
 'Austin Airport',
 '09:13',
 'Nkoxville Airport',
 '09:27',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA157',
 'San Jose Airport',
 '06:22',
 'Buffalo Airport',
 '06:22',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA208',
 'Reading Airport',
 '04:57',
 'Rochester Airport',
 '06:11',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA39',
 'Houston Airport',
 '16:30',
 'Trenton Airport',
 '16:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL125',
 'Salt Lake Airport',
 '11:57',
 'San Jose Airport',
 '11:11',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL189',
 'Cairo Airport',
 '08:14',
 'San Jose Airport',
 '13:18',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta133',
 'Cleveland Airport',
 '13:26',
 'Richmond Airport',
 '16:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta175',
 'St. Louis Airport',
 '23:31',
 'Jacksonville Airport',
 '01:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL194',
 'Jersey City Airport',
 '10:14',
 'Macon Airport',
 '10:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta166',
 'Lansing Airport',
 '11:31',
 'San Francisco Airport',
 '11:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA170',
 'Minneapolis Airport',
 '02:24',
 'Frankfort Airport',
 '02:24',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA257',
 'Richmond Airport',
 '21:46',
 'Philadelphia Airport',
 '23:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir254',
 'Atlantic City Airport',
 '05:27',
 'Trenton Airport',
 '06:29',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA125',
 'Lincoln Airport',
 '15:05',
 'San Antonio Airport',
 '19:13',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir185',
 'Green Bay Airport',
 '21:35',
 'Albany Airport',
 '00:47',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW48',
 'Salt Lake Airport',
 '18:12',
 'Madison Airport',
 '19:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW106',
 'Hershey Airport',
 '13:27',
 'Green Bay Airport',
 '16:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL258',
 'Phoenix Airport',
 '11:24',
 'Lansing Airport',
 '14:37',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW50',
 'San Francisco Airport',
 '07:03',
 'Toledo Airport',
 '11:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir120',
 'Toledo Airport',
 '17:08',
 'Columbus Airport',
 '18:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA167',
 'Orlando Airport',
 '00:43',
 'Norfolk Airport',
 '02:55',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW130',
 'Worcester Airport',
 '23:45',
 'Tallahassee Airport',
 '00:56',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir46',
 'St. Louis Airport',
 '18:40',
 'Baltimore Airport',
 '22:52',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL156',
 'Syracuse Airport',
 '09:02',
 'Lincoln Airport',
 '11:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir159',
 'San Jose Airport',
 '21:41',
 'New York City Airport',
 '23:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL111',
 'Oakland Airport',
 '13:46',
 'Kansas City Airport',
 '15:54',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA243',
 'Oakland Airport',
 '11:56',
 'Reading Airport',
 '11:01',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA211',
 'Seattle Airport',
 '17:51',
 'Toledo Airport',
 '21:02',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA189',
 'Cleveland Airport',
 '12:11',
 'Nkoxville Airport',
 '16:17',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL44',
 'Raleigh Airport',
 '12:33',
 'Tulsa Airport',
 '13:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA187',
 'Norfolk Airport',
 '07:08',
 'Lincoln Airport',
 '11:11',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA206',
 'Austin Airport',
 '17:43',
 'Nkoxville Airport',
 '18:53',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL122',
 'Brooklyn Airport',
 '03:07',
 'Anchorage Airport',
 '03:08',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA201',
 'Anchorage Airport',
 '10:31',
 'Cincinnati Airport',
 '10:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA114',
 'Rochester Airport',
 '22:59',
 'Seattle Airport',
 '02:59',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA80',
 'Madison Airport',
 '02:58',
 'Albany Airport',
 '03:05',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW119',
 'Macon Airport',
 '06:40',
 'SpringField Airport',
 '09:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW92',
 'Macon Airport',
 '12:24',
 'Flint Airport',
 '13:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW269',
 'Ann Arbor Airport',
 '06:04',
 'Austin Airport',
 '07:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW131',
 'Oakland Airport',
 '23:55',
 'Burbank Airport',
 '03:02',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA147',
 'St. Paul Airport',
 '14:01',
 'Lincoln Airport',
 '17:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW47',
 'Tempa Airport',
 '09:28',
 'Green Bay Airport',
 '10:35',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA175',
 'Buffalo Airport',
 '07:24',
 'Tacoma Airport',
 '09:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA5',
 'Tulsa Airport',
 '04:59',
 'Jersey City Airport',
 '07:13',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA161',
 'Nkoxville Airport',
 '17:30',
 'Chicago Airport',
 '22:34',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW197',
 'Sacramento Airport',
 '20:40',
 'Dallas Airport',
 '23:50',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta60',
 'Dayton Airport',
 '10:46',
 'Durham Airport',
 '14:59',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir88',
 'Albany Airport',
 '18:03',
 'Minneapolis Airport',
 '18:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA184',
 'Boulder Airport',
 '00:33',
 'Detroit Airport',
 '04:34',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW146',
 'Tallahassee Airport',
 '07:52',
 'Hershey Airport',
 '11:56',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir91',
 'Green Bay Airport',
 '13:50',
 'Lansing Airport',
 '13:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA6',
 'Jacksonville Airport',
 '03:29',
 'Nkoxville Airport',
 '04:43',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW294',
 'Denver Airport',
 '11:43',
 'Madison Airport',
 '11:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL12',
 'San Francisco Airport',
 '13:18',
 'Houston Airport',
 '15:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW268',
 'Albany Airport',
 '20:25',
 'Detroit Airport',
 '21:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta241',
 'SpringField Airport',
 '14:33',
 'Detroit Airport',
 '14:38',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA174',
 'Macon Airport',
 '11:10',
 'Tallahassee Airport',
 '14:12',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA270',
 'Atlantic City Airport',
 '16:08',
 'Madison Airport',
 '19:17',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta196',
 'Athens Airport',
 '15:25',
 'Chicago Airport',
 '16:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW4',
 'Memphis Airport',
 '11:58',
 'Rochester Airport',
 '14:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta59',
 'Syracuse Airport',
 '21:42',
 'San Jose Airport',
 '00:43',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW212',
 'Brooklyn Airport',
 '22:17',
 'Sacramento Airport',
 '01:18',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta207',
 'New Orleans Airport',
 '08:43',
 'Toledo Airport',
 '12:47',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA157',
 'Oakland Airport',
 '21:32',
 'Indianapolis Airport',
 '23:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta204',
 'San Francisco Airport',
 '22:19',
 'Ann Arbor Airport',
 '22:30',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA138',
 'Brooklyn Airport',
 '02:56',
 'Cleveland Airport',
 '04:01',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta281',
 'San Antonio Airport',
 '05:06',
 'Charleston Airport',
 '08:09',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL31',
 'Athens Airport',
 '10:20',
 'Kansas City Airport',
 '13:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW112',
 'Miami Airport',
 '15:57',
 'Lincoln Airport',
 '19:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA52',
 'Dayton Airport',
 '00:40',
 'Pittsburgh Airport',
 '01:45',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW158',
 'Minneapolis Airport',
 '11:01',
 'Atlanta Airport',
 '13:12',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir21',
 'Seattle Airport',
 '05:03',
 'Albany Airport',
 '09:07',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA39',
 'Orlando Airport',
 '21:05',
 'Juneau Airport',
 '00:10',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir11',
 'San Francisco Airport',
 '17:47',
 'Portland Airport',
 '21:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA171',
 'San Francisco Airport',
 '02:47',
 'Dayton Airport',
 '06:47',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW175',
 'New Orleans Airport',
 '18:02',
 'Juneau Airport',
 '23:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA131',
 'Toledo Airport',
 '12:38',
 'Milwukee Airport',
 '16:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA44',
 'San Diego Airport',
 '02:17',
 'Hershey Airport',
 '03:19',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA158',
 'Seattle Airport',
 '13:53',
 'Reading Airport',
 '14:58',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA233',
 'Sacramento Airport',
 '22:54',
 'New York City Airport',
 '03:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta20',
 'Lincoln Airport',
 '04:44',
 'Anchorage Airport',
 '07:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta91',
 'Tallahassee Airport',
 '01:08',
 'St. Louis Airport',
 '02:17',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA52',
 'Syracuse Airport',
 '19:57',
 'Houston Airport',
 '22:10',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA184',
 'Dayton Airport',
 '05:03',
 'Lansing Airport',
 '06:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL21',
 'San Diego Airport',
 '08:39',
 'Madison Airport',
 '08:39',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir125',
 'Norfolk Airport',
 '13:30',
 'Dayton Airport',
 '17:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta132',
 'Oakland Airport',
 '08:30',
 'Green Bay Airport',
 '13:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL149',
 'Frankfort Airport',
 '01:15',
 'Tacoma Airport',
 '06:20',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA202',
 'Detroit Airport',
 '08:34',
 'Dayton Airport',
 '13:40',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA133',
 'Syracuse Airport',
 '21:06',
 'Chicago Airport',
 '01:15',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA259',
 'Philadelphia Airport',
 '10:37',
 'San Antonio Airport',
 '14:47',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL129',
 'Burbank Airport',
 '11:16',
 'Ann Arbor Airport',
 '15:23',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA181',
 'Green Bay Airport',
 '19:12',
 'Cincinnati Airport',
 '22:22',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA82',
 'Tallahassee Airport',
 '23:16',
 'Rochester Airport',
 '00:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA139',
 'Baltimore Airport',
 '08:44',
 'Jacksonville Airport',
 '12:51',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA212',
 'Lansing Airport',
 '15:05',
 'Indianapolis Airport',
 '17:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA97',
 'Dallas Airport',
 '17:24',
 'Cleveland Airport',
 '20:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA53',
 'Hershey Airport',
 '22:50',
 'St. Paul Airport',
 '02:04',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW150',
 'St. Paul Airport',
 '01:04',
 'Charleston Airport',
 '04:06',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA196',
 'Jersey City Airport',
 '21:35',
 'Juneau Airport',
 '21:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir232',
 'Dayton Airport',
 '04:59',
 'Norfolk Airport',
 '07:12',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL253',
 'Juneau Airport',
 '01:02',
 'Tallahassee Airport',
 '03:14',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL91',
 'Cleveland Airport',
 '19:46',
 'Houston Airport',
 '20:52',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA169',
 'Madison Airport',
 '00:48',
 'Athens Airport',
 '02:02',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA162',
 'Norfolk Airport',
 '10:06',
 'Waco Airport',
 '12:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL9',
 'Memphis Airport',
 '15:57',
 'Toledo Airport',
 '16:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir100',
 'Raleigh Airport',
 '00:56',
 'Worcester Airport',
 '04:01',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir166',
 'Nkoxville Airport',
 '04:10',
 'Baltimore Airport',
 '05:17',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW40',
 'Cairo Airport',
 '00:00',
 'Frankfort Airport',
 '03:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW133',
 'Tallahassee Airport',
 '20:44',
 'Oakland Airport',
 '21:44',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL116',
 'New York City Airport',
 '18:13',
 'Richmond Airport',
 '20:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA286',
 'Raleigh Airport',
 '03:22',
 'San Antonio Airport',
 '05:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta131',
 'Atlantic City Airport',
 '13:03',
 'Tulsa Airport',
 '16:12',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA35',
 'Durham Airport',
 '17:24',
 'New York City Airport',
 '17:25',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA67',
 'Dayton Airport',
 '05:22',
 'St. Louis Airport',
 '08:22',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW21',
 'New Orleans Airport',
 '04:47',
 'Tacoma Airport',
 '07:53',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA223',
 'Raleigh Airport',
 '16:13',
 'Dayton Airport',
 '19:25',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta98',
 'Portland Airport',
 '20:41',
 'Phoenix Airport',
 '23:52',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA11',
 'SpringField Airport',
 '00:55',
 'Phoenix Airport',
 '01:58',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA272',
 'St. Paul Airport',
 '03:48',
 'Cairo Airport',
 '03:51',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA159',
 'Charleston Airport',
 '00:16',
 'Austin Airport',
 '04:20',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW77',
 'Columbus Airport',
 '20:23',
 'SpringField Airport',
 '23:27',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL192',
 'Tallahassee Airport',
 '19:46',
 'Lincoln Airport',
 '20:56',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA218',
 'San Francisco Airport',
 '05:49',
 'Detroit Airport',
 '06:49',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA194',
 'Chicago Airport',
 '12:14',
 'Syracuse Airport',
 '12:18',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta159',
 'Tacoma Airport',
 '10:03',
 'Charleston Airport',
 '12:07',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta262',
 'Buffalo Airport',
 '17:14',
 'Boston Airport',
 '21:28',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA110',
 'Houston Airport',
 '22:14',
 'Portland Airport',
 '00:22',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA129',
 'Frankfort Airport',
 '13:38',
 'Philadelphia Airport',
 '15:46',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW87',
 'Atlantic City Airport',
 '01:45',
 'Pittsburgh Airport',
 '04:54',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA292',
 'Pittsburgh Airport',
 '09:36',
 'Lansing Airport',
 '10:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA142',
 'Raleigh Airport',
 '00:17',
 'Buffalo Airport',
 '03:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA109',
 'New York City Airport',
 '00:55',
 'Madison Airport',
 '02:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA231',
 'Madison Airport',
 '16:34',
 'Albany Airport',
 '21:46',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA215',
 'Oakland Airport',
 '09:33',
 'San Jose Airport',
 '09:38',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA176',
 'Worcester Airport',
 '04:15',
 'St. Paul Airport',
 '06:24',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA25',
 'Worcester Airport',
 '13:46',
 'Madison Airport',
 '16:48',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA9',
 'Dayton Airport',
 '06:02',
 'San Francisco Airport',
 '07:16',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW59',
 'San Antonio Airport',
 '15:42',
 'Macon Airport',
 '18:48',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL164',
 'Philadelphia Airport',
 '15:50',
 'San Jose Airport',
 '19:01',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA167',
 'Green Bay Airport',
 '06:05',
 'Jacksonville Airport',
 '09:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW55',
 'Hershey Airport',
 '00:19',
 'Atlanta Airport',
 '03:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA247',
 'Portland Airport',
 '09:01',
 'Tacoma Airport',
 '10:07',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta164',
 'Frankfort Airport',
 '07:09',
 'Philadelphia Airport',
 '11:16',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW149',
 'Salt Lake Airport',
 '00:50',
 'Lansing Airport',
 '03:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA153',
 'Minneapolis Airport',
 '00:01',
 'Green Bay Airport',
 '02:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW200',
 'Raleigh Airport',
 '06:41',
 'Richmond Airport',
 '08:55',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA131',
 'San Antonio Airport',
 '08:39',
 'Dayton Airport',
 '09:44',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA13',
 'Dayton Airport',
 '05:42',
 'Portland Airport',
 '06:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW233',
 'Nkoxville Airport',
 '08:51',
 'Charleston Airport',
 '08:52',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA176',
 'Albany Airport',
 '07:06',
 'San Francisco Airport',
 '07:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta247',
 'Syracuse Airport',
 '04:46',
 'Toledo Airport',
 '08:49',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA66',
 'Los Angles Airport',
 '04:00',
 'Worcester Airport',
 '08:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW194',
 'Burbank Airport',
 '08:39',
 'Lincoln Airport',
 '11:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL103',
 'Albany Airport',
 '20:26',
 'Portland Airport',
 '22:28',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir256',
 'Denver Airport',
 '20:45',
 'Chicago Airport',
 '22:46',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA269',
 'Frankfort Airport',
 '00:27',
 'Milwukee Airport',
 '04:34',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir56',
 'Tempa Airport',
 '23:21',
 'Phoenix Airport',
 '03:34',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA115',
 'Cleveland Airport',
 '11:19',
 'Detroit Airport',
 '15:27',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA1',
 'Nkoxville Airport',
 '12:55',
 'Tulsa Airport',
 '13:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA23',
 'Dayton Airport',
 '03:00',
 'Denver Airport',
 '03:11',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta108',
 'Worcester Airport',
 '06:19',
 'San Jose Airport',
 '06:19',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA8',
 'Indianapolis Airport',
 '02:10',
 'Oakland Airport',
 '05:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW171',
 'San Antonio Airport',
 '08:08',
 'Columbus Airport',
 '11:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA39',
 'Phoenix Airport',
 '15:52',
 'Nashville Airport',
 '16:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir215',
 'St. Paul Airport',
 '00:00',
 'San Francisco Airport',
 '04:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta63',
 'Atlantic City Airport',
 '09:01',
 'Denver Airport',
 '09:06',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL163',
 'Macon Airport',
 '09:06',
 'Boston Airport',
 '12:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA249',
 'Ann Arbor Airport',
 '14:40',
 'Seattle Airport',
 '18:52',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW172',
 'Tacoma Airport',
 '16:11',
 'Albany Airport',
 '18:19',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA213',
 'Norfolk Airport',
 '11:34',
 'Buffalo Airport',
 '15:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta155',
 'New Orleans Airport',
 '06:48',
 'Milwukee Airport',
 '10:57',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW171',
 'Madison Airport',
 '07:49',
 'Jacksonville Airport',
 '11:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir68',
 'Burbank Airport',
 '21:45',
 'Atlantic City Airport',
 '00:55',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir42',
 'Philadelphia Airport',
 '15:13',
 'Tulsa Airport',
 '19:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW102',
 'Durham Airport',
 '10:44',
 'Tulsa Airport',
 '11:51',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA127',
 'Syracuse Airport',
 '11:16',
 'Green Bay Airport',
 '11:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA110',
 'Indianapolis Airport',
 '10:20',
 'Boston Airport',
 '11:28',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA12',
 'Ann Arbor Airport',
 '00:58',
 'Portland Airport',
 '03:08',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA77',
 'Tacoma Airport',
 '08:58',
 'Columbus Airport',
 '12:04',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW16',
 'Columbus Airport',
 '20:19',
 'Austin Airport',
 '20:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir30',
 'Denver Airport',
 '04:14',
 'Lexington Airport',
 '05:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL213',
 'Oklahoma City Airport',
 '07:26',
 'Tulsa Airport',
 '09:38',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA127',
 'Boston Airport',
 '03:21',
 'Phoenix Airport',
 '07:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta208',
 'Pittsburgh Airport',
 '03:08',
 'Kansas City Airport',
 '03:15',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW40',
 'Brooklyn Airport',
 '11:38',
 'Reading Airport',
 '11:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW117',
 'Ann Arbor Airport',
 '03:30',
 'Rochester Airport',
 '07:40',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL209',
 'San Jose Airport',
 '15:49',
 'Charleston Airport',
 '19:53',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW191',
 'Milwukee Airport',
 '19:50',
 'Cleveland Airport',
 '20:56',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW179',
 'New Orleans Airport',
 '23:56',
 'San Jose Airport',
 '00:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir72',
 'Reading Airport',
 '03:36',
 'Cincinnati Airport',
 '03:42',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA62',
 'Lexington Airport',
 '15:56',
 'Raleigh Airport',
 '18:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA69',
 'Anchorage Airport',
 '09:39',
 'New Orleans Airport',
 '13:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta284',
 'Toledo Airport',
 '20:13',
 'Trenton Airport',
 '20:21',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta48',
 'Milwukee Airport',
 '00:00',
 'Athens Airport',
 '04:05',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir145',
 'Pittsburgh Airport',
 '20:37',
 'Nashville Airport',
 '22:37',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW168',
 'Anchorage Airport',
 '11:12',
 'Lansing Airport',
 '12:19',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA186',
 'Oakland Airport',
 '03:37',
 'Phoenix Airport',
 '07:38',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA140',
 'Denver Airport',
 '07:15',
 'Lansing Airport',
 '08:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA185',
 'Houston Airport',
 '06:56',
 'Cincinnati Airport',
 '10:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA14',
 'Toledo Airport',
 '13:24',
 'Albany Airport',
 '17:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA130',
 'Dallas Airport',
 '05:19',
 'Anchorage Airport',
 '09:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL197',
 'Worcester Airport',
 '00:40',
 'Houston Airport',
 '03:44',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA267',
 'Lansing Airport',
 '09:00',
 'Atlantic City Airport',
 '10:05',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW263',
 'Flint Airport',
 '11:55',
 'Burbank Airport',
 '11:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA43',
 'Tulsa Airport',
 '02:58',
 'Charleston Airport',
 '03:11',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta26',
 'Portland Airport',
 '03:43',
 'Nashville Airport',
 '05:48',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA122',
 'Cincinnati Airport',
 '08:57',
 'Sacramento Airport',
 '12:00',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA211',
 'Norfolk Airport',
 '20:02',
 'Los Angles Airport',
 '23:08',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir127',
 'Pittsburgh Airport',
 '14:17',
 'Salt Lake Airport',
 '16:19',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA34',
 'Oklahoma City Airport',
 '18:52',
 'Lansing Airport',
 '22:00',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta65',
 'St. Louis Airport',
 '12:00',
 'Milwukee Airport',
 '12:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW101',
 'Frankfort Airport',
 '07:25',
 'Milwukee Airport',
 '10:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA274',
 'Waco Airport',
 '00:58',
 'Burbank Airport',
 '03:07',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir278',
 'Toledo Airport',
 '06:55',
 'Rochester Airport',
 '10:01',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA195',
 'Burbank Airport',
 '00:34',
 'Worcester Airport',
 '03:45',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA12',
 'Orlando Airport',
 '10:11',
 'Hershey Airport',
 '12:18',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir80',
 'Boston Airport',
 '05:56',
 'Seattle Airport',
 '10:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA256',
 'Juneau Airport',
 '09:01',
 'Rochester Airport',
 '13:02',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA4',
 'Tacoma Airport',
 '22:07',
 'Columbus Airport',
 '22:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW45',
 'Tacoma Airport',
 '17:48',
 'Miami Airport',
 '20:53',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir195',
 'Sacramento Airport',
 '08:55',
 'Portland Airport',
 '12:06',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW7',
 'St. Paul Airport',
 '16:56',
 'Austin Airport',
 '18:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL215',
 'Raleigh Airport',
 '07:52',
 'Boston Airport',
 '09:03',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW132',
 'Memphis Airport',
 '18:31',
 'New Orleans Airport',
 '18:33',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW33',
 'Portland Airport',
 '13:45',
 'Atlanta Airport',
 '14:57',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA180',
 'Brooklyn Airport',
 '17:05',
 'Albany Airport',
 '17:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA191',
 'Brooklyn Airport',
 '10:07',
 'New Orleans Airport',
 '14:08',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL86',
 'New Orleans Airport',
 '01:43',
 'San Diego Airport',
 '05:52',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA167',
 'Waco Airport',
 '07:17',
 'Milwukee Airport',
 '07:18',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir223',
 'San Jose Airport',
 '06:07',
 'Dayton Airport',
 '06:09',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir13',
 'Indianapolis Airport',
 '00:34',
 'Jacksonville Airport',
 '01:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA64',
 'Chicago Airport',
 '03:56',
 'Tacoma Airport',
 '06:04',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta264',
 'Austin Airport',
 '18:17',
 'Brooklyn Airport',
 '18:20',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW3',
 'Waco Airport',
 '06:32',
 'Tempa Airport',
 '10:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta135',
 'Denver Airport',
 '20:09',
 'Tempa Airport',
 '21:11',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW282',
 'Flint Airport',
 '03:06',
 'Boston Airport',
 '04:12',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA201',
 'Cincinnati Airport',
 '21:19',
 'Lexington Airport',
 '23:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA124',
 'SpringField Airport',
 '13:32',
 'Syracuse Airport',
 '16:37',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir265',
 'Trenton Airport',
 '09:19',
 'Jacksonville Airport',
 '13:25',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA28',
 'Green Bay Airport',
 '04:33',
 'Buffalo Airport',
 '05:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA66',
 'Norfolk Airport',
 '00:16',
 'Syracuse Airport',
 '00:21',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA30',
 'Buffalo Airport',
 '20:45',
 'Tacoma Airport',
 '22:59',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA215',
 'Boston Airport',
 '12:15',
 'Buffalo Airport',
 '12:20',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL143',
 'Lincoln Airport',
 '02:22',
 'Orlando Airport',
 '07:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA13',
 'Lincoln Airport',
 '06:24',
 'Juneau Airport',
 '10:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW28',
 'Tulsa Airport',
 '17:50',
 'Juneau Airport',
 '18:00',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA45',
 'Seattle Airport',
 '07:36',
 'Atlantic City Airport',
 '10:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW175',
 'Trenton Airport',
 '15:14',
 'Dayton Airport',
 '17:24',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta261',
 'Lansing Airport',
 '08:39',
 'Ann Arbor Airport',
 '10:49',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW109',
 'Austin Airport',
 '17:01',
 'SpringField Airport',
 '20:02',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA1',
 'Columbus Airport',
 '05:51',
 'Seattle Airport',
 '05:57',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir189',
 'Ann Arbor Airport',
 '04:20',
 'Tacoma Airport',
 '06:27',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA269',
 'Baltimore Airport',
 '04:42',
 'San Jose Airport',
 '06:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta12',
 'Kansas City Airport',
 '02:02',
 'San Francisco Airport',
 '05:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL49',
 'Denver Airport',
 '14:54',
 'Cleveland Airport',
 '14:56',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir140',
 'Lincoln Airport',
 '16:41',
 'Flint Airport',
 '16:54',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA136',
 'Salt Lake Airport',
 '08:32',
 'Milwukee Airport',
 '11:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta279',
 'Cairo Airport',
 '14:46',
 'Charleston Airport',
 '17:56',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW253',
 'Cincinnati Airport',
 '14:59',
 'Atlantic City Airport',
 '17:05',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW289',
 'Cleveland Airport',
 '09:03',
 'Trenton Airport',
 '11:05',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA88',
 'Salt Lake Airport',
 '00:37',
 'Tallahassee Airport',
 '05:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir194',
 'Macon Airport',
 '08:36',
 'Dayton Airport',
 '10:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA129',
 'Cleveland Airport',
 '00:58',
 'San Jose Airport',
 '01:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA296',
 'Boulder Airport',
 '11:17',
 'Hershey Airport',
 '15:29',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL40',
 'Tacoma Airport',
 '22:45',
 'Green Bay Airport',
 '01:54',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA154',
 'Austin Airport',
 '03:46',
 'Tulsa Airport',
 '05:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL107',
 'New York City Airport',
 '01:09',
 'Durham Airport',
 '05:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir261',
 'SpringField Airport',
 '07:34',
 'Toledo Airport',
 '09:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir138',
 'Atlanta Airport',
 '13:08',
 'Atlantic City Airport',
 '15:16',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW211',
 'Green Bay Airport',
 '08:33',
 'Seattle Airport',
 '08:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta169',
 'Denver Airport',
 '03:10',
 'Jacksonville Airport',
 '08:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA189',
 'Atlantic City Airport',
 '09:18',
 'Milwukee Airport',
 '10:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA271',
 'Boston Airport',
 '22:30',
 'Dayton Airport',
 '01:42',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL69',
 'Memphis Airport',
 '18:17',
 'Tempa Airport',
 '19:18',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA135',
 'Anchorage Airport',
 '14:16',
 'Miami Airport',
 '19:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir133',
 'Norfolk Airport',
 '11:44',
 'Atlanta Airport',
 '12:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA15',
 'Macon Airport',
 '14:33',
 'Tallahassee Airport',
 '16:34',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW5',
 'Buffalo Airport',
 '10:34',
 'Trenton Airport',
 '13:35',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW198',
 'Dayton Airport',
 '13:27',
 'Worcester Airport',
 '15:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL226',
 'Brooklyn Airport',
 '11:19',
 'Ann Arbor Airport',
 '12:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir276',
 'Ann Arbor Airport',
 '06:09',
 'Tallahassee Airport',
 '09:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA226',
 'Reading Airport',
 '11:15',
 'Toledo Airport',
 '15:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW198',
 'Memphis Airport',
 '08:35',
 'Indianapolis Airport',
 '09:47',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW195',
 'Nkoxville Airport',
 '11:02',
 'Boston Airport',
 '12:02',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW15',
 'Columbus Airport',
 '20:23',
 'Salt Lake Airport',
 '00:35',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL200',
 'Green Bay Airport',
 '12:12',
 'Miami Airport',
 '16:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW52',
 'Boston Airport',
 '01:10',
 'Syracuse Airport',
 '05:24',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir218',
 'Boulder Airport',
 '08:06',
 'St. Paul Airport',
 '10:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW287',
 'St. Louis Airport',
 '03:15',
 'Chicago Airport',
 '05:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA115',
 'Burbank Airport',
 '13:53',
 'San Jose Airport',
 '17:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA58',
 'Kansas City Airport',
 '08:43',
 'Philadelphia Airport',
 '10:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW143',
 'Tacoma Airport',
 '18:15',
 'Milwukee Airport',
 '19:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA25',
 'Cairo Airport',
 '12:48',
 'Frankfort Airport',
 '12:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW270',
 'Cairo Airport',
 '13:18',
 'Boston Airport',
 '17:27',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA149',
 'Frankfort Airport',
 '20:17',
 'Cincinnati Airport',
 '21:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA260',
 'Richmond Airport',
 '18:24',
 'Burbank Airport',
 '19:37',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA91',
 'Dayton Airport',
 '20:12',
 'Trenton Airport',
 '22:13',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL173',
 'Tallahassee Airport',
 '06:12',
 'Seattle Airport',
 '08:16',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir226',
 'Waco Airport',
 '00:56',
 'Atlantic City Airport',
 '03:02',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL266',
 'Pittsburgh Airport',
 '15:27',
 'Salt Lake Airport',
 '20:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta18',
 'Burbank Airport',
 '13:49',
 'Cairo Airport',
 '13:54',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir253',
 'Tempa Airport',
 '00:00',
 'Reading Airport',
 '00:07',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW5',
 'Milwukee Airport',
 '07:28',
 'Miami Airport',
 '08:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir146',
 'New Orleans Airport',
 '02:21',
 'Green Bay Airport',
 '02:28',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA48',
 'Waco Airport',
 '14:55',
 'Reading Airport',
 '17:56',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA249',
 'Pittsburgh Airport',
 '11:05',
 'Detroit Airport',
 '12:18',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA296',
 'Charleston Airport',
 '07:54',
 'Buffalo Airport',
 '09:03',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW170',
 'Nkoxville Airport',
 '04:59',
 'Lansing Airport',
 '07:02',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW214',
 'Lexington Airport',
 '04:11',
 'San Francisco Airport',
 '05:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL32',
 'Indianapolis Airport',
 '18:49',
 'Detroit Airport',
 '21:49',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir272',
 'Cairo Airport',
 '18:36',
 'Waco Airport',
 '21:40',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir107',
 'Pittsburgh Airport',
 '01:15',
 'Athens Airport',
 '04:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA238',
 'Tempa Airport',
 '09:12',
 'Toledo Airport',
 '10:12',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA18',
 'Madison Airport',
 '18:27',
 'San Antonio Airport',
 '18:31',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA82',
 'Reading Airport',
 '16:57',
 'Oakland Airport',
 '19:58',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA170',
 'New York City Airport',
 '22:22',
 'Rochester Airport',
 '22:32',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir152',
 'Buffalo Airport',
 '02:10',
 'Lansing Airport',
 '05:10',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL294',
 'Frankfort Airport',
 '06:01',
 'Buffalo Airport',
 '06:15',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA279',
 'Dallas Airport',
 '13:01',
 'Syracuse Airport',
 '14:09',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW249',
 'Detroit Airport',
 '22:36',
 'Phoenix Airport',
 '00:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta211',
 'Tacoma Airport',
 '18:39',
 'Raleigh Airport',
 '20:39',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA0',
 'Tempa Airport',
 '21:09',
 'Albany Airport',
 '21:23',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA219',
 'Hershey Airport',
 '03:14',
 'Madison Airport',
 '03:25',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL8',
 'Cleveland Airport',
 '12:42',
 'New York City Airport',
 '16:42',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA70',
 'Columbus Airport',
 '16:09',
 'Philadelphia Airport',
 '18:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA250',
 'Frankfort Airport',
 '18:38',
 'Orlando Airport',
 '22:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir122',
 'Athens Airport',
 '10:13',
 'Oklahoma City Airport',
 '12:15',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA205',
 'Athens Airport',
 '23:22',
 'Rochester Airport',
 '01:22',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta186',
 'Rochester Airport',
 '11:18',
 'Macon Airport',
 '13:32',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA3',
 'Detroit Airport',
 '21:07',
 'Lexington Airport',
 '23:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA267',
 'Tallahassee Airport',
 '17:10',
 'Nkoxville Airport',
 '17:11',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir87',
 'Oakland Airport',
 '07:05',
 'Salt Lake Airport',
 '10:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL252',
 'San Francisco Airport',
 '02:42',
 'Cairo Airport',
 '05:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA165',
 'Indianapolis Airport',
 '02:00',
 'Trenton Airport',
 '05:02',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta206',
 'Columbus Airport',
 '17:38',
 'Juneau Airport',
 '17:49',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir7',
 'San Diego Airport',
 '16:41',
 'Ann Arbor Airport',
 '21:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA233',
 'Ann Arbor Airport',
 '01:00',
 'Brooklyn Airport',
 '04:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA15',
 'Dayton Airport',
 '03:52',
 'Sacramento Airport',
 '05:02',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta198',
 'Tacoma Airport',
 '11:37',
 'Kansas City Airport',
 '12:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA282',
 'Lansing Airport',
 '07:51',
 'Dayton Airport',
 '10:58',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA79',
 'San Diego Airport',
 '18:14',
 'Brooklyn Airport',
 '21:25',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta285',
 'Rochester Airport',
 '20:21',
 'St. Paul Airport',
 '23:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA30',
 'Richmond Airport',
 '12:55',
 'Boston Airport',
 '15:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta238',
 'Juneau Airport',
 '03:08',
 'Hershey Airport',
 '06:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir3',
 'Durham Airport',
 '22:31',
 'Norfolk Airport',
 '02:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA176',
 'Pittsburgh Airport',
 '05:29',
 'Los Angles Airport',
 '08:31',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA220',
 'Albany Airport',
 '23:38',
 'Lansing Airport',
 '03:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA134',
 'St. Louis Airport',
 '23:44',
 'Tulsa Airport',
 '03:54',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA38',
 'Minneapolis Airport',
 '04:34',
 'Portland Airport',
 '05:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA117',
 'Buffalo Airport',
 '17:38',
 'Cairo Airport',
 '17:42',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA283',
 'Reading Airport',
 '16:29',
 'Rochester Airport',
 '20:43',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta254',
 'Boston Airport',
 '20:31',
 'Kansas City Airport',
 '01:37',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA144',
 'Athens Airport',
 '15:59',
 'Burbank Airport',
 '17:00',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW226',
 'Nashville Airport',
 '17:30',
 'Pittsburgh Airport',
 '22:42',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA298',
 'St. Louis Airport',
 '22:47',
 'Philadelphia Airport',
 '22:55',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW8',
 'Toledo Airport',
 '02:32',
 'Trenton Airport',
 '07:41',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW253',
 'Sacramento Airport',
 '19:32',
 'Miami Airport',
 '21:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW124',
 'Nkoxville Airport',
 '00:41',
 'San Antonio Airport',
 '03:41',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA277',
 'Indianapolis Airport',
 '02:16',
 'Worcester Airport',
 '02:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir282',
 'Atlantic City Airport',
 '18:03',
 'Tacoma Airport',
 '21:04',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA294',
 'Ann Arbor Airport',
 '10:45',
 'Cleveland Airport',
 '14:48',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir187',
 'Trenton Airport',
 '10:29',
 'Juneau Airport',
 '10:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW110',
 'Flint Airport',
 '05:38',
 'Raleigh Airport',
 '09:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA292',
 'Pittsburgh Airport',
 '00:54',
 'Detroit Airport',
 '02:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL131',
 'Memphis Airport',
 '01:26',
 'Lansing Airport',
 '01:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA101',
 'Nkoxville Airport',
 '09:18',
 'Madison Airport',
 '10:20',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL92',
 'Oklahoma City Airport',
 '07:08',
 'Burbank Airport',
 '09:08',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA232',
 'Seattle Airport',
 '17:31',
 'Dallas Airport',
 '20:42',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL102',
 'Pittsburgh Airport',
 '16:41',
 'San Jose Airport',
 '19:55',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA14',
 'Los Angles Airport',
 '01:50',
 'Milwukee Airport',
 '01:54',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA9',
 'Anchorage Airport',
 '08:04',
 'Tallahassee Airport',
 '09:13',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta224',
 'San Jose Airport',
 '17:32',
 'Jersey City Airport',
 '20:43',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA210',
 'Frankfort Airport',
 '10:20',
 'Syracuse Airport',
 '13:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA98',
 'Cleveland Airport',
 '05:06',
 'Philadelphia Airport',
 '06:09',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA271',
 'Juneau Airport',
 '23:13',
 'Syracuse Airport',
 '01:23',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA106',
 'Portland Airport',
 '20:49',
 'Miami Airport',
 '00:49',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA272',
 'Indianapolis Airport',
 '13:17',
 'Los Angles Airport',
 '15:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA178',
 'Phoenix Airport',
 '14:27',
 'Frankfort Airport',
 '18:34',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA264',
 'Nkoxville Airport',
 '21:43',
 'Indianapolis Airport',
 '23:47',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA249',
 'Dayton Airport',
 '05:19',
 'Tacoma Airport',
 '05:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA226',
 'Denver Airport',
 '09:14',
 'Miami Airport',
 '12:28',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW223',
 'Philadelphia Airport',
 '03:15',
 'Richmond Airport',
 '05:21',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW3',
 'Juneau Airport',
 '07:47',
 'Atlanta Airport',
 '10:55',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir74',
 'Detroit Airport',
 '11:41',
 'Dayton Airport',
 '14:55',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW139',
 'Miami Airport',
 '05:03',
 'Nashville Airport',
 '05:15',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir287',
 'SpringField Airport',
 '17:42',
 'Baltimore Airport',
 '18:49',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA24',
 'Tulsa Airport',
 '20:50',
 'Los Angles Airport',
 '23:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir15',
 'Oakland Airport',
 '22:18',
 'Chicago Airport',
 '01:21',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW135',
 'Reading Airport',
 '08:04',
 'Dallas Airport',
 '09:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW64',
 'Seattle Airport',
 '01:56',
 'Kansas City Airport',
 '05:09',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW41',
 'Jersey City Airport',
 '06:45',
 'San Jose Airport',
 '07:48',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA93',
 'Oakland Airport',
 '15:22',
 'Indianapolis Airport',
 '18:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA186',
 'Syracuse Airport',
 '07:48',
 'Macon Airport',
 '10:49',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta81',
 'Miami Airport',
 '23:39',
 'Seattle Airport',
 '03:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA78',
 'Anchorage Airport',
 '14:39',
 'Tallahassee Airport',
 '16:41',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA132',
 'New Orleans Airport',
 '14:31',
 'Atlanta Airport',
 '14:45',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW285',
 'Raleigh Airport',
 '14:43',
 'Tacoma Airport',
 '14:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA55',
 'Houston Airport',
 '08:17',
 'Columbus Airport',
 '12:31',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA8',
 'Dallas Airport',
 '12:55',
 'Tallahassee Airport',
 '14:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW248',
 'Jersey City Airport',
 '12:57',
 'Memphis Airport',
 '14:02',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir34',
 'Chicago Airport',
 '10:33',
 'Lexington Airport',
 '11:37',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL225',
 'Tacoma Airport',
 '21:55',
 'Jacksonville Airport',
 '01:06',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta17',
 'Reading Airport',
 '04:33',
 'Tulsa Airport',
 '08:43',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL106',
 'San Antonio Airport',
 '21:48',
 'Pittsburgh Airport',
 '21:02',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA259',
 'Norfolk Airport',
 '00:13',
 'Cincinnati Airport',
 '04:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA110',
 'Charleston Airport',
 '15:09',
 'Flint Airport',
 '19:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA268',
 'Boulder Airport',
 '14:01',
 'Lincoln Airport',
 '15:10',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA38',
 'Richmond Airport',
 '22:59',
 'Tempa Airport',
 '23:02',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW125',
 'Jacksonville Airport',
 '17:58',
 'Salt Lake Airport',
 '19:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW264',
 'Sacramento Airport',
 '11:06',
 'Baltimore Airport',
 '15:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta139',
 'Tacoma Airport',
 '19:48',
 'New Orleans Airport',
 '23:53',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL146',
 'Macon Airport',
 '22:54',
 'Anchorage Airport',
 '23:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL13',
 'Baltimore Airport',
 '05:51',
 'Phoenix Airport',
 '07:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA130',
 'San Francisco Airport',
 '17:48',
 'Albany Airport',
 '19:55',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL232',
 'Worcester Airport',
 '22:11',
 'Nashville Airport',
 '02:23',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL94',
 'Los Angles Airport',
 '04:57',
 'Kansas City Airport',
 '09:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA218',
 'Milwukee Airport',
 '12:26',
 'Oklahoma City Airport',
 '14:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW204',
 'Tempa Airport',
 '16:50',
 'Burbank Airport',
 '20:02',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL291',
 'Jersey City Airport',
 '08:24',
 'Los Angles Airport',
 '09:27',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA241',
 'Waco Airport',
 '14:31',
 'Chicago Airport',
 '17:44',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta257',
 'Frankfort Airport',
 '20:38',
 'Buffalo Airport',
 '22:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir99',
 'Hershey Airport',
 '22:42',
 'Pittsburgh Airport',
 '00:52',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta283',
 'Brooklyn Airport',
 '09:10',
 'Toledo Airport',
 '10:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW153',
 'Richmond Airport',
 '00:07',
 'Salt Lake Airport',
 '01:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA227',
 'Indianapolis Airport',
 '19:17',
 'Ann Arbor Airport',
 '21:27',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta179',
 'Detroit Airport',
 '07:03',
 'Dallas Airport',
 '10:04',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA135',
 'Miami Airport',
 '21:33',
 'Tacoma Airport',
 '23:41',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW230',
 'Juneau Airport',
 '12:08',
 'Dallas Airport',
 '12:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW166',
 'Cairo Airport',
 '18:37',
 'Syracuse Airport',
 '21:41',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta233',
 'Raleigh Airport',
 '07:09',
 'Juneau Airport',
 '08:19',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW113',
 'Tacoma Airport',
 '07:21',
 'Oklahoma City Airport',
 '10:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL70',
 'Anchorage Airport',
 '09:40',
 'Norfolk Airport',
 '14:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW157',
 'Lansing Airport',
 '14:38',
 'Jersey City Airport',
 '15:41',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA213',
 'New York City Airport',
 '07:36',
 'Macon Airport',
 '10:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA2',
 'Jersey City Airport',
 '12:29',
 'Trenton Airport',
 '13:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA229',
 'Portland Airport',
 '12:21',
 'St. Louis Airport',
 '13:21',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW208',
 'Syracuse Airport',
 '23:02',
 'Tacoma Airport',
 '02:02',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta61',
 'Minneapolis Airport',
 '15:37',
 'SpringField Airport',
 '17:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA131',
 'Miami Airport',
 '03:23',
 'San Francisco Airport',
 '07:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta227',
 'Indianapolis Airport',
 '12:19',
 'Dayton Airport',
 '16:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta21',
 'Atlantic City Airport',
 '17:32',
 'New Orleans Airport',
 '21:41',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW194',
 'Ann Arbor Airport',
 '22:54',
 'Waco Airport',
 '23:06',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta141',
 'Boulder Airport',
 '03:26',
 'Lincoln Airport',
 '03:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir191',
 'Macon Airport',
 '10:52',
 'Cleveland Airport',
 '10:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir230',
 'San Jose Airport',
 '04:31',
 'Dallas Airport',
 '04:32',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA242',
 'Lincoln Airport',
 '10:10',
 'Albany Airport',
 '14:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW0',
 'Oklahoma City Airport',
 '00:54',
 'Madison Airport',
 '00:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA163',
 'Cairo Airport',
 '21:08',
 'Anchorage Airport',
 '02:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW128',
 'Jacksonville Airport',
 '23:08',
 'Philadelphia Airport',
 '01:20',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA91',
 'Atlanta Airport',
 '13:33',
 'San Diego Airport',
 '14:46',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW168',
 'Minneapolis Airport',
 '06:17',
 'Atlanta Airport',
 '06:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW258',
 'Brooklyn Airport',
 '15:08',
 'Nashville Airport',
 '19:11',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA25',
 'Cincinnati Airport',
 '23:13',
 'Columbus Airport',
 '03:17',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir297',
 'Atlantic City Airport',
 '15:49',
 'Oakland Airport',
 '17:57',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta126',
 'Tacoma Airport',
 '06:58',
 'Minneapolis Airport',
 '10:11',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL228',
 'Reading Airport',
 '18:55',
 'Nashville Airport',
 '18:05',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW222',
 'Pittsburgh Airport',
 '15:01',
 'Green Bay Airport',
 '18:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta192',
 'Kansas City Airport',
 '04:41',
 'Los Angles Airport',
 '05:50',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA270',
 'Frankfort Airport',
 '21:53',
 'Rochester Airport',
 '01:05',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA290',
 'Ann Arbor Airport',
 '18:32',
 'Brooklyn Airport',
 '18:45',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir82',
 'Atlantic City Airport',
 '03:25',
 'Athens Airport',
 '05:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir85',
 'New York City Airport',
 '15:58',
 'Lexington Airport',
 '18:10',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA195',
 'Los Angles Airport',
 '23:08',
 'Kansas City Airport',
 '02:18',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA125',
 'Minneapolis Airport',
 '16:00',
 'Rochester Airport',
 '16:05',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL1',
 'Durham Airport',
 '08:56',
 'Milwukee Airport',
 '11:03',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir240',
 'Orlando Airport',
 '12:49',
 'Athens Airport',
 '13:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir63',
 'San Jose Airport',
 '00:06',
 'Minneapolis Airport',
 '01:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA191',
 'Tacoma Airport',
 '02:47',
 'Oklahoma City Airport',
 '04:50',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA21',
 'Trenton Airport',
 '14:00',
 'Madison Airport',
 '17:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW207',
 'Oakland Airport',
 '00:15',
 'Raleigh Airport',
 '02:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA11',
 'Phoenix Airport',
 '13:16',
 'Memphis Airport',
 '17:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta161',
 'Brooklyn Airport',
 '02:57',
 'Macon Airport',
 '03:10',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir105',
 'Cleveland Airport',
 '23:32',
 'San Francisco Airport',
 '03:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW221',
 'Austin Airport',
 '05:44',
 'Miami Airport',
 '07:57',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW16',
 'Durham Airport',
 '05:20',
 'Tempa Airport',
 '07:26',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA174',
 'Juneau Airport',
 '23:57',
 'Tempa Airport',
 '03:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA209',
 'Denver Airport',
 '02:09',
 'Chicago Airport',
 '02:23',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir110',
 'Tulsa Airport',
 '10:56',
 'Nkoxville Airport',
 '10:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA238',
 'Kansas City Airport',
 '12:19',
 'Sacramento Airport',
 '15:27',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta293',
 'New Orleans Airport',
 '15:19',
 'Juneau Airport',
 '18:28',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW62',
 'Richmond Airport',
 '17:53',
 'Buffalo Airport',
 '18:56',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA88',
 'Miami Airport',
 '04:54',
 'Oakland Airport',
 '05:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA165',
 'Dallas Airport',
 '08:29',
 'Durham Airport',
 '09:41',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA297',
 'Tallahassee Airport',
 '16:37',
 'Phoenix Airport',
 '20:51',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA172',
 'Hershey Airport',
 '04:28',
 'Anchorage Airport',
 '05:33',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW281',
 'Atlantic City Airport',
 '04:27',
 'Pittsburgh Airport',
 '05:29',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW286',
 'Frankfort Airport',
 '13:18',
 'St. Paul Airport',
 '14:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta50',
 'Toledo Airport',
 '01:11',
 'Madison Airport',
 '02:16',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW22',
 'San Diego Airport',
 '04:46',
 'Raleigh Airport',
 '07:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir128',
 'Sacramento Airport',
 '01:05',
 'Rochester Airport',
 '01:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA136',
 'Athens Airport',
 '21:59',
 'Buffalo Airport',
 '00:02',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta239',
 'Sacramento Airport',
 '05:24',
 'Tacoma Airport',
 '10:24',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA207',
 'Seattle Airport',
 '20:36',
 'Syracuse Airport',
 '23:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta90',
 'Syracuse Airport',
 '19:05',
 'St. Louis Airport',
 '20:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW69',
 'Phoenix Airport',
 '15:04',
 'Lexington Airport',
 '16:05',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA55',
 'Reading Airport',
 '09:50',
 'Pittsburgh Airport',
 '10:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA90',
 'Pittsburgh Airport',
 '07:22',
 'Ann Arbor Airport',
 '11:27',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL39',
 'Los Angles Airport',
 '09:30',
 'Green Bay Airport',
 '11:43',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW6',
 'Oklahoma City Airport',
 '14:04',
 'Madison Airport',
 '18:15',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA166',
 'Raleigh Airport',
 '19:19',
 'Austin Airport',
 '20:29',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW230',
 'Phoenix Airport',
 '03:19',
 'Cincinnati Airport',
 '06:28',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA36',
 'Boston Airport',
 '15:49',
 'Hershey Airport',
 '17:57',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta215',
 'San Jose Airport',
 '15:27',
 'Lexington Airport',
 '17:41',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA219',
 'Flint Airport',
 '03:17',
 'Raleigh Airport',
 '07:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW114',
 'Salt Lake Airport',
 '01:17',
 'Cleveland Airport',
 '03:23',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA99',
 'Durham Airport',
 '05:56',
 'Burbank Airport',
 '10:09',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA47',
 'San Antonio Airport',
 '01:32',
 'Worcester Airport',
 '02:40',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta291',
 'Indianapolis Airport',
 '18:11',
 'Hershey Airport',
 '21:19',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW246',
 'Waco Airport',
 '07:50',
 'Tacoma Airport',
 '10:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir274',
 'San Diego Airport',
 '18:54',
 'Rochester Airport',
 '18:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA125',
 'Philadelphia Airport',
 '03:22',
 'Dayton Airport',
 '04:36',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA56',
 'Nashville Airport',
 '09:38',
 'Brooklyn Airport',
 '09:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA245',
 'Waco Airport',
 '18:50',
 'Toledo Airport',
 '21:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW1',
 'Ann Arbor Airport',
 '12:51',
 'Boston Airport',
 '13:03',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA104',
 'Flint Airport',
 '13:49',
 'Madison Airport',
 '14:52',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA86',
 'Dayton Airport',
 '12:05',
 'Nashville Airport',
 '16:10',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta16',
 'Ann Arbor Airport',
 '00:00',
 'Tallahassee Airport',
 '01:02',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA44',
 'Philadelphia Airport',
 '08:43',
 'Seattle Airport',
 '13:52',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW224',
 'Lincoln Airport',
 '10:28',
 'Madison Airport',
 '10:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir28',
 'New Orleans Airport',
 '00:10',
 'Jacksonville Airport',
 '01:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA25',
 'SpringField Airport',
 '10:11',
 'Milwukee Airport',
 '13:24',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL188',
 'Philadelphia Airport',
 '21:00',
 'Lansing Airport',
 '00:08',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL240',
 'Minneapolis Airport',
 '00:02',
 'Philadelphia Airport',
 '00:03',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA116',
 'Jacksonville Airport',
 '18:45',
 'Kansas City Airport',
 '22:58',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta252',
 'Minneapolis Airport',
 '07:15',
 'Tulsa Airport',
 '08:27',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir24',
 'Sacramento Airport',
 '11:27',
 'Lincoln Airport',
 '15:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW244',
 'Syracuse Airport',
 '21:41',
 'Brooklyn Airport',
 '21:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL223',
 'New Orleans Airport',
 '02:54',
 'San Jose Airport',
 '06:01',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA46',
 'Phoenix Airport',
 '19:21',
 'Albany Airport',
 '23:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta31',
 'Lexington Airport',
 '01:35',
 'Atlanta Airport',
 '03:40',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA180',
 'Albany Airport',
 '15:13',
 'San Antonio Airport',
 '17:13',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta120',
 'Anchorage Airport',
 '16:52',
 'Pittsburgh Airport',
 '18:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir183',
 'Tulsa Airport',
 '13:26',
 'Orlando Airport',
 '17:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA133',
 'Tacoma Airport',
 '19:40',
 'SpringField Airport',
 '00:42',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta162',
 'Brooklyn Airport',
 '13:49',
 'Columbus Airport',
 '15:53',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA121',
 'Charleston Airport',
 '02:49',
 'Flint Airport',
 '04:52',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW217',
 'Tempa Airport',
 '16:29',
 'Trenton Airport',
 '17:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA255',
 'Atlantic City Airport',
 '15:34',
 'Indianapolis Airport',
 '19:44',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA11',
 'Nashville Airport',
 '08:04',
 'Boston Airport',
 '12:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL242',
 'Lansing Airport',
 '22:49',
 'Atlantic City Airport',
 '02:55',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA257',
 'Durham Airport',
 '15:53',
 'Jersey City Airport',
 '16:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta276',
 'Raleigh Airport',
 '16:27',
 'Chicago Airport',
 '18:27',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir243',
 'Raleigh Airport',
 '03:17',
 'Anchorage Airport',
 '07:19',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW52',
 'Waco Airport',
 '08:39',
 'Tempa Airport',
 '09:48',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir35',
 'Toledo Airport',
 '23:10',
 'Tallahassee Airport',
 '03:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW245',
 'Boulder Airport',
 '06:10',
 'Trenton Airport',
 '08:23',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir27',
 'Worcester Airport',
 '21:13',
 'Frankfort Airport',
 '22:17',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA283',
 'SpringField Airport',
 '08:24',
 'Reading Airport',
 '09:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA215',
 'Oakland Airport',
 '23:24',
 'Houston Airport',
 '23:38',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA247',
 'Tempa Airport',
 '22:08',
 'Richmond Airport',
 '23:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta191',
 'Nkoxville Airport',
 '16:08',
 'Los Angles Airport',
 '17:18',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA230',
 'New York City Airport',
 '06:52',
 'Minneapolis Airport',
 '06:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta216',
 'Atlanta Airport',
 '07:31',
 'Tacoma Airport',
 '10:44',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA93',
 'Buffalo Airport',
 '00:17',
 'Austin Airport',
 '00:17',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA205',
 'Tacoma Airport',
 '09:34',
 'Raleigh Airport',
 '09:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA37',
 'Frankfort Airport',
 '03:21',
 'Dayton Airport',
 '04:29',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA71',
 'Durham Airport',
 '20:56',
 'Syracuse Airport',
 '23:01',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta103',
 'San Antonio Airport',
 '02:06',
 'San Jose Airport',
 '06:16',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL16',
 'Oklahoma City Airport',
 '22:31',
 'Tacoma Airport',
 '01:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW54',
 'Milwukee Airport',
 '08:06',
 'Phoenix Airport',
 '10:11',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL99',
 'Waco Airport',
 '16:18',
 'Atlantic City Airport',
 '19:29',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW88',
 'Norfolk Airport',
 '11:49',
 'Trenton Airport',
 '13:53',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta210',
 'Detroit Airport',
 '17:08',
 'Cairo Airport',
 '19:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA288',
 'St. Louis Airport',
 '01:26',
 'New Orleans Airport',
 '03:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL289',
 'Juneau Airport',
 '10:34',
 'Tacoma Airport',
 '10:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta49',
 'Trenton Airport',
 '18:42',
 'Brooklyn Airport',
 '19:53',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA230',
 'Austin Airport',
 '15:56',
 'Burbank Airport',
 '15:03',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW47',
 'Chicago Airport',
 '13:07',
 'Anchorage Airport',
 '14:14',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA109',
 'Boulder Airport',
 '10:14',
 'Albany Airport',
 '14:21',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir31',
 'Cleveland Airport',
 '18:32',
 'Lansing Airport',
 '22:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL114',
 'Atlanta Airport',
 '20:50',
 'Brooklyn Airport',
 '21:03',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA87',
 'Atlantic City Airport',
 '04:58',
 'SpringField Airport',
 '07:58',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL74',
 'Burbank Airport',
 '01:08',
 'Milwukee Airport',
 '05:18',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL33',
 'Minneapolis Airport',
 '06:43',
 'Richmond Airport',
 '09:43',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW82',
 'Dayton Airport',
 '03:34',
 'Orlando Airport',
 '06:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA263',
 'Brooklyn Airport',
 '17:44',
 'Syracuse Airport',
 '19:53',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA223',
 'Salt Lake Airport',
 '10:19',
 'Waco Airport',
 '12:20',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta32',
 'SpringField Airport',
 '13:46',
 'Hershey Airport',
 '15:57',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW70',
 'Macon Airport',
 '20:17',
 'Green Bay Airport',
 '22:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta142',
 'Hershey Airport',
 '13:16',
 'Jacksonville Airport',
 '15:24',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir186',
 'Los Angles Airport',
 '22:11',
 'Juneau Airport',
 '00:12',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA27',
 'Jacksonville Airport',
 '22:29',
 'Lansing Airport',
 '02:33',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA213',
 'Miami Airport',
 '10:50',
 'Oklahoma City Airport',
 '13:55',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA181',
 'Cincinnati Airport',
 '03:39',
 'Boulder Airport',
 '03:53',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL54',
 'Toledo Airport',
 '00:43',
 'Miami Airport',
 '03:54',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA287',
 'SpringField Airport',
 '17:19',
 'New Orleans Airport',
 '19:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta82',
 'Toledo Airport',
 '16:03',
 'San Jose Airport',
 '17:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA106',
 'Toledo Airport',
 '00:42',
 'Burbank Airport',
 '03:52',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA40',
 'Kansas City Airport',
 '01:37',
 'Indianapolis Airport',
 '04:46',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta298',
 'Cincinnati Airport',
 '10:17',
 'Milwukee Airport',
 '14:24',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW44',
 'Waco Airport',
 '20:54',
 'Tulsa Airport',
 '21:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA286',
 'Los Angles Airport',
 '03:05',
 'Athens Airport',
 '05:08',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta172',
 'Baltimore Airport',
 '13:49',
 'Norfolk Airport',
 '15:00',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA76',
 'Miami Airport',
 '10:13',
 'Portland Airport',
 '12:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA237',
 'St. Paul Airport',
 '17:11',
 'Syracuse Airport',
 '17:14',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW239',
 'San Jose Airport',
 '12:58',
 'Detroit Airport',
 '16:05',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL206',
 'Richmond Airport',
 '19:07',
 'Waco Airport',
 '23:20',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL35',
 'Sacramento Airport',
 '11:49',
 'Baltimore Airport',
 '13:55',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL205',
 'Oakland Airport',
 '19:03',
 'Oklahoma City Airport',
 '19:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW277',
 'Boston Airport',
 '07:00',
 'Boulder Airport',
 '09:12',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA280',
 'Syracuse Airport',
 '14:03',
 'Nashville Airport',
 '17:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL274',
 'Oklahoma City Airport',
 '19:16',
 'SpringField Airport',
 '21:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW111',
 'Frankfort Airport',
 '01:04',
 'Detroit Airport',
 '02:05',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA139',
 'Tempa Airport',
 '10:00',
 'Austin Airport',
 '13:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA27',
 'Milwukee Airport',
 '01:14',
 'Tulsa Airport',
 '04:23',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW127',
 'Frankfort Airport',
 '02:17',
 'Athens Airport',
 '02:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA250',
 'Tulsa Airport',
 '02:31',
 'Anchorage Airport',
 '05:32',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir121',
 'Memphis Airport',
 '04:25',
 'Juneau Airport',
 '07:32',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL231',
 'Denver Airport',
 '11:22',
 'Cleveland Airport',
 '14:22',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA281',
 'Norfolk Airport',
 '16:27',
 'Austin Airport',
 '16:34',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta51',
 'Charleston Airport',
 '08:02',
 'St. Louis Airport',
 '12:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW44',
 'Trenton Airport',
 '15:43',
 'Tacoma Airport',
 '16:45',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW10',
 'Baltimore Airport',
 '02:10',
 'Madison Airport',
 '04:22',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA46',
 'Chicago Airport',
 '00:38',
 'San Jose Airport',
 '04:49',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA3',
 'Juneau Airport',
 '18:30',
 'Phoenix Airport',
 '19:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA212',
 'SpringField Airport',
 '16:14',
 'Nkoxville Airport',
 '19:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA283',
 'Orlando Airport',
 '15:18',
 'Frankfort Airport',
 '17:28',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA64',
 'Lincoln Airport',
 '01:13',
 'Chicago Airport',
 '03:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta237',
 'Brooklyn Airport',
 '12:16',
 'Ann Arbor Airport',
 '14:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA241',
 'Indianapolis Airport',
 '13:25',
 'Hershey Airport',
 '13:33',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL161',
 'Lexington Airport',
 '06:43',
 'San Antonio Airport',
 '06:43',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir136',
 'Milwukee Airport',
 '14:04',
 'Lincoln Airport',
 '16:07',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA171',
 'Tacoma Airport',
 '14:03',
 'Macon Airport',
 '17:11',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL112',
 'Jacksonville Airport',
 '10:40',
 'Ann Arbor Airport',
 '14:43',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta109',
 'Tallahassee Airport',
 '05:01',
 'San Diego Airport',
 '09:11',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW37',
 'Anchorage Airport',
 '01:17',
 'Denver Airport',
 '02:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA40',
 'Austin Airport',
 '15:15',
 'Waco Airport',
 '17:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL166',
 'Trenton Airport',
 '08:50',
 'Madison Airport',
 '13:56',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA33',
 'Phoenix Airport',
 '00:58',
 'Raleigh Airport',
 '02:04',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW183',
 'Columbus Airport',
 '01:44',
 'San Antonio Airport',
 '03:51',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL275',
 'Syracuse Airport',
 '17:28',
 'Cleveland Airport',
 '19:31',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW202',
 'Rochester Airport',
 '00:04',
 'Syracuse Airport',
 '01:04',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW36',
 'Charleston Airport',
 '18:32',
 'Philadelphia Airport',
 '19:40',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL53',
 'Houston Airport',
 '18:03',
 'Tacoma Airport',
 '22:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA69',
 'Philadelphia Airport',
 '12:09',
 'Indianapolis Airport',
 '16:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA287',
 'Miami Airport',
 '01:46',
 'Oklahoma City Airport',
 '01:00',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir288',
 'Portland Airport',
 '23:42',
 'Houston Airport',
 '02:54',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir81',
 'Cleveland Airport',
 '04:04',
 'San Antonio Airport',
 '05:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA116',
 'Atlanta Airport',
 '01:59',
 'Albany Airport',
 '02:13',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW66',
 'Norfolk Airport',
 '13:45',
 'Lansing Airport',
 '15:54',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA127',
 'Juneau Airport',
 '08:19',
 'Seattle Airport',
 '10:33',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA130',
 'Atlanta Airport',
 '22:06',
 'Denver Airport',
 '02:11',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW104',
 'Norfolk Airport',
 '21:42',
 'Tempa Airport',
 '23:47',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW279',
 'Houston Airport',
 '18:03',
 'Buffalo Airport',
 '21:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA198',
 'Athens Airport',
 '23:55',
 'Phoenix Airport',
 '23:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW74',
 'Philadelphia Airport',
 '14:58',
 'Portland Airport',
 '14:05',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta27',
 'Burbank Airport',
 '08:24',
 'Miami Airport',
 '11:35',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA188',
 'Baltimore Airport',
 '20:46',
 'Orlando Airport',
 '01:59',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA74',
 'Burbank Airport',
 '18:34',
 'Dayton Airport',
 '20:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW33',
 'Reading Airport',
 '09:44',
 'SpringField Airport',
 '09:46',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA169',
 'Green Bay Airport',
 '08:10',
 'Dayton Airport',
 '08:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA296',
 'Jacksonville Airport',
 '11:04',
 'Tallahassee Airport',
 '14:08',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA96',
 'Richmond Airport',
 '06:20',
 'Albany Airport',
 '10:30',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW241',
 'San Antonio Airport',
 '12:25',
 'Oakland Airport',
 '17:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta149',
 'Charleston Airport',
 '04:09',
 'Boston Airport',
 '07:20',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA75',
 'Los Angles Airport',
 '12:03',
 'Frankfort Airport',
 '14:12',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW245',
 'San Jose Airport',
 '23:19',
 'Denver Airport',
 '01:26',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA116',
 'San Diego Airport',
 '11:36',
 'Cleveland Airport',
 '12:37',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL26',
 'Raleigh Airport',
 '04:40',
 'Norfolk Airport',
 '07:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA84',
 'Philadelphia Airport',
 '02:09',
 'Frankfort Airport',
 '05:12',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA210',
 'Syracuse Airport',
 '13:08',
 'Phoenix Airport',
 '17:22',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta97',
 'Macon Airport',
 '10:59',
 'Albany Airport',
 '15:10',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA37',
 'Flint Airport',
 '20:10',
 'Tacoma Airport',
 '00:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA96',
 'Juneau Airport',
 '05:21',
 'Dayton Airport',
 '05:34',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA176',
 'Madison Airport',
 '10:17',
 'Jacksonville Airport',
 '10:23',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA147',
 'Ann Arbor Airport',
 '05:42',
 'Waco Airport',
 '09:51',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW19',
 'SpringField Airport',
 '14:11',
 'Burbank Airport',
 '15:24',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta266',
 'Brooklyn Airport',
 '09:59',
 'Burbank Airport',
 '13:05',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA94',
 'Lexington Airport',
 '14:50',
 'Oakland Airport',
 '16:59',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir260',
 'Oklahoma City Airport',
 '13:36',
 'Chicago Airport',
 '14:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA56',
 'Buffalo Airport',
 '21:51',
 'New Orleans Airport',
 '00:05',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA102',
 'San Diego Airport',
 '15:12',
 'Phoenix Airport',
 '15:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA28',
 'Columbus Airport',
 '05:29',
 'Dayton Airport',
 '07:42',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA257',
 'Sacramento Airport',
 '08:50',
 'New York City Airport',
 '10:00',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA192',
 'Jersey City Airport',
 '17:52',
 'Pittsburgh Airport',
 '17:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW152',
 'Jacksonville Airport',
 '13:00',
 'Lansing Airport',
 '15:10',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA36',
 'Denver Airport',
 '13:31',
 'Boston Airport',
 '16:43',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA225',
 'Juneau Airport',
 '16:42',
 'Anchorage Airport',
 '20:43',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA284',
 'Atlanta Airport',
 '19:55',
 'Oakland Airport',
 '21:00',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA206',
 'Nkoxville Airport',
 '11:11',
 'Boston Airport',
 '15:13',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir39',
 'St. Paul Airport',
 '09:19',
 'Sacramento Airport',
 '09:30',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA161',
 'St. Louis Airport',
 '04:29',
 'Rochester Airport',
 '05:40',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW293',
 'Lexington Airport',
 '18:23',
 'Chicago Airport',
 '21:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW120',
 'Salt Lake Airport',
 '15:11',
 'Lexington Airport',
 '17:13',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir50',
 'Richmond Airport',
 '08:51',
 'Dallas Airport',
 '10:58',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA253',
 'Sacramento Airport',
 '12:20',
 'San Antonio Airport',
 '14:24',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW292',
 'Waco Airport',
 '12:59',
 'Syracuse Airport',
 '13:08',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA248',
 'Cairo Airport',
 '14:48',
 'Tallahassee Airport',
 '14:50',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL75',
 'Phoenix Airport',
 '00:55',
 'Portland Airport',
 '04:04',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA10',
 'Anchorage Airport',
 '08:38',
 'San Diego Airport',
 '12:42',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW233',
 'Richmond Airport',
 '08:13',
 'Tempa Airport',
 '12:22',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA52',
 'San Jose Airport',
 '09:00',
 'Ann Arbor Airport',
 '14:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA166',
 'Jacksonville Airport',
 '07:01',
 'Philadelphia Airport',
 '11:01',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA141',
 'Salt Lake Airport',
 '18:43',
 'Dayton Airport',
 '22:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA42',
 'Kansas City Airport',
 '07:37',
 'Brooklyn Airport',
 '09:47',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL77',
 'Tacoma Airport',
 '07:24',
 'Durham Airport',
 '10:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW223',
 'Pittsburgh Airport',
 '15:25',
 'Burbank Airport',
 '19:35',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL283',
 'San Jose Airport',
 '12:36',
 'Miami Airport',
 '16:47',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA251',
 'Worcester Airport',
 '22:01',
 'Richmond Airport',
 '00:02',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA173',
 'Anchorage Airport',
 '04:54',
 'Hershey Airport',
 '07:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir47',
 'Houston Airport',
 '08:33',
 'Worcester Airport',
 '09:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA248',
 'Atlantic City Airport',
 '00:28',
 'Boulder Airport',
 '03:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA172',
 'Macon Airport',
 '04:27',
 'Brooklyn Airport',
 '04:33',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW31',
 'Waco Airport',
 '14:16',
 'Macon Airport',
 '17:22',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA282',
 'Brooklyn Airport',
 '04:20',
 'Flint Airport',
 '08:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL260',
 'Atlantic City Airport',
 '01:31',
 'Madison Airport',
 '02:38',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW95',
 'Trenton Airport',
 '19:08',
 'Cairo Airport',
 '21:08',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW119',
 'Milwukee Airport',
 '19:29',
 'Chicago Airport',
 '23:35',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir246',
 'Tallahassee Airport',
 '14:37',
 'Albany Airport',
 '17:48',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW276',
 'Tempa Airport',
 '12:10',
 'Waco Airport',
 '16:14',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA184',
 'Madison Airport',
 '09:32',
 'Chicago Airport',
 '11:39',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA87',
 'St. Louis Airport',
 '04:23',
 'Anchorage Airport',
 '07:25',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW250',
 'Hershey Airport',
 '08:29',
 'San Jose Airport',
 '11:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL15',
 'Nkoxville Airport',
 '02:36',
 'Norfolk Airport',
 '05:42',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW160',
 'Houston Airport',
 '08:18',
 'Austin Airport',
 '08:32',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir102',
 'San Diego Airport',
 '20:46',
 'Tallahassee Airport',
 '23:00',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW174',
 'Dayton Airport',
 '00:06',
 'Boulder Airport',
 '04:08',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta88',
 'Philadelphia Airport',
 '07:40',
 'Tacoma Airport',
 '12:42',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA200',
 'Tulsa Airport',
 '11:27',
 'Baltimore Airport',
 '12:41',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir259',
 'Anchorage Airport',
 '18:07',
 'Jacksonville Airport',
 '19:08',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL238',
 'Cleveland Airport',
 '05:09',
 'Denver Airport',
 '09:12',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta96',
 'Orlando Airport',
 '04:32',
 'Oakland Airport',
 '07:39',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA240',
 'Tacoma Airport',
 '23:26',
 'Boulder Airport',
 '00:33',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA265',
 'San Francisco Airport',
 '05:02',
 'Tacoma Airport',
 '09:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW235',
 'Waco Airport',
 '00:50',
 'Ann Arbor Airport',
 '02:50',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA50',
 'Reading Airport',
 '07:12',
 'Tallahassee Airport',
 '10:16',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta112',
 'Cairo Airport',
 '15:03',
 'Burbank Airport',
 '15:03',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA136',
 'San Francisco Airport',
 '04:13',
 'Charleston Airport',
 '05:26',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA218',
 'Anchorage Airport',
 '20:49',
 'St. Paul Airport',
 '23:02',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL93',
 'Jersey City Airport',
 '02:43',
 'Phoenix Airport',
 '04:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta89',
 'Nashville Airport',
 '02:33',
 'Pittsburgh Airport',
 '04:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL55',
 'Rochester Airport',
 '10:57',
 'Philadelphia Airport',
 '12:10',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA72',
 'Hershey Airport',
 '23:31',
 'Richmond Airport',
 '02:38',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL24',
 'Boulder Airport',
 '22:39',
 'Durham Airport',
 '00:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir66',
 'New Orleans Airport',
 '21:30',
 'San Diego Airport',
 '01:37',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA261',
 'Milwukee Airport',
 '02:59',
 'Dayton Airport',
 '02:13',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA280',
 'Houston Airport',
 '04:55',
 'Austin Airport',
 '04:01',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta183',
 'Brooklyn Airport',
 '16:23',
 'Boulder Airport',
 '17:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW220',
 'Baltimore Airport',
 '05:14',
 'Waco Airport',
 '07:16',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW299',
 'Sacramento Airport',
 '04:29',
 'Denver Airport',
 '06:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta295',
 'Rochester Airport',
 '13:43',
 'Sacramento Airport',
 '13:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta199',
 'Indianapolis Airport',
 '10:25',
 'Flint Airport',
 '13:39',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA49',
 'Denver Airport',
 '07:31',
 'Seattle Airport',
 '10:37',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta54',
 'Atlantic City Airport',
 '23:02',
 'San Jose Airport',
 '03:14',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('CA199',
 'Pittsburgh Airport',
 '20:45',
 'Houston Airport',
 '23:47',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW118',
 'Trenton Airport',
 '23:49',
 'Pittsburgh Airport',
 '01:00',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA291',
 'Portland Airport',
 '18:22',
 'San Diego Airport',
 '22:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir196',
 'Phoenix Airport',
 '22:21',
 'Houston Airport',
 '01:32',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW34',
 'Raleigh Airport',
 '23:17',
 'Chicago Airport',
 '02:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA99',
 'Tallahassee Airport',
 '10:44',
 'Milwukee Airport',
 '13:57',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA273',
 'Dallas Airport',
 '14:57',
 'San Jose Airport',
 '14:01',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA133',
 'SpringField Airport',
 '04:32',
 'Syracuse Airport',
 '07:32',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA128',
 'Memphis Airport',
 '14:34',
 'Salt Lake Airport',
 '14:34',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL281',
 'Albany Airport',
 '12:06',
 'Orlando Airport',
 '15:07',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW176',
 'Atlanta Airport',
 '17:35',
 'Richmond Airport',
 '17:45',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta271',
 'Oakland Airport',
 '02:27',
 'Cincinnati Airport',
 '05:38',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA29',
 'Salt Lake Airport',
 '20:08',
 'Milwukee Airport',
 '00:19',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW234',
 'Albany Airport',
 '23:22',
 'Los Angles Airport',
 '02:36',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA35',
 'Cairo Airport',
 '06:28',
 'Nkoxville Airport',
 '10:36',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW15',
 'Seattle Airport',
 '07:03',
 'Oakland Airport',
 '10:06',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir98',
 'Cairo Airport',
 '21:57',
 'SpringField Airport',
 '22:07',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA187',
 'Houston Airport',
 '20:02',
 'Los Angles Airport',
 '22:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA114',
 'Albany Airport',
 '06:48',
 'Juneau Airport',
 '09:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL219',
 'Cleveland Airport',
 '06:20',
 'Portland Airport',
 '09:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA120',
 'Tempa Airport',
 '04:51',
 'Oakland Airport',
 '08:51',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL96',
 'Anchorage Airport',
 '07:47',
 'SpringField Airport',
 '08:54',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW59',
 'Reading Airport',
 '05:28',
 'Columbus Airport',
 '06:35',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL101',
 'Salt Lake Airport',
 '06:04',
 'New York City Airport',
 '07:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta193',
 'Detroit Airport',
 '22:54',
 'Cleveland Airport',
 '01:05',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW266',
 'San Jose Airport',
 '15:11',
 'Lexington Airport',
 '16:22',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA59',
 'St. Paul Airport',
 '19:45',
 'San Jose Airport',
 '19:53',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW98',
 'Juneau Airport',
 '11:59',
 'St. Louis Airport',
 '11:08',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta173',
 'New York City Airport',
 '03:04',
 'Orlando Airport',
 '04:16',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW298',
 'Richmond Airport',
 '21:03',
 'Anchorage Airport',
 '00:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA272',
 'Milwukee Airport',
 '13:54',
 'Minneapolis Airport',
 '17:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA244',
 'Boulder Airport',
 '03:12',
 'Tacoma Airport',
 '05:18',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW272',
 'Albany Airport',
 '08:30',
 'Atlanta Airport',
 '09:42',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta5',
 'Dayton Airport',
 '01:18',
 'San Francisco Airport',
 '01:21',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA100',
 'Norfolk Airport',
 '18:58',
 'Cincinnati Airport',
 '19:08',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir227',
 'Miami Airport',
 '09:03',
 'New York City Airport',
 '12:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir19',
 'Nashville Airport',
 '18:17',
 'Jacksonville Airport',
 '21:29',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA299',
 'Boulder Airport',
 '05:36',
 'Oklahoma City Airport',
 '09:48',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta46',
 'Dayton Airport',
 '20:29',
 'Lincoln Airport',
 '22:43',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA134',
 'Albany Airport',
 '02:46',
 'SpringField Airport',
 '03:49',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA177',
 'Boston Airport',
 '07:46',
 'Dayton Airport',
 '09:54',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('UA119',
 'Rochester Airport',
 '12:58',
 'Albany Airport',
 '16:10',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta85',
 'Atlantic City Airport',
 '00:54',
 'Jersey City Airport',
 '01:07',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA160',
 'Jacksonville Airport',
 '12:39',
 'Seattle Airport',
 '12:45',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA20',
 'Frankfort Airport',
 '02:05',
 'Green Bay Airport',
 '04:12',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL287',
 'Atlantic City Airport',
 '03:50',
 'San Francisco Airport',
 '05:52',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL273',
 'Jacksonville Airport',
 '18:00',
 'Tempa Airport',
 '21:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir160',
 'San Antonio Airport',
 '08:48',
 'Ann Arbor Airport',
 '12:51',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA293',
 'Reading Airport',
 '02:17',
 'Buffalo Airport',
 '07:25',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA167',
 'Miami Airport',
 '04:20',
 'Dallas Airport',
 '08:34',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA32',
 'Indianapolis Airport',
 '00:08',
 'Lincoln Airport',
 '02:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA252',
 'Phoenix Airport',
 '10:18',
 'Albany Airport',
 '12:23',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL2',
 'Miami Airport',
 '06:00',
 'Los Angles Airport',
 '09:14',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA174',
 'Buffalo Airport',
 '07:55',
 'Dallas Airport',
 '09:05',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir176',
 'Atlanta Airport',
 '00:29',
 'Juneau Airport',
 '04:34',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA138',
 'Kansas City Airport',
 '10:00',
 'Lansing Airport',
 '12:00',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW152',
 'Detroit Airport',
 '02:47',
 'Lincoln Airport',
 '04:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA1',
 'Boulder Airport',
 '04:47',
 'Dayton Airport',
 '05:59',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta9',
 'Dayton Airport',
 '22:14',
 'San Jose Airport',
 '01:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir268',
 'Cincinnati Airport',
 '09:02',
 'Lincoln Airport',
 '10:11',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta130',
 'St. Louis Airport',
 '03:24',
 'St. Paul Airport',
 '05:31',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA142',
 'Chicago Airport',
 '23:49',
 'Lexington Airport',
 '23:56',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL78',
 'St. Louis Airport',
 '19:40',
 'San Antonio Airport',
 '20:46',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA17',
 'Memphis Airport',
 '21:40',
 'Richmond Airport',
 '00:48',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW123',
 'Portland Airport',
 '08:41',
 'Cairo Airport',
 '08:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW278',
 'Burbank Airport',
 '12:22',
 'Syracuse Airport',
 '15:31',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA161',
 'Seattle Airport',
 '02:31',
 'Juneau Airport',
 '05:41',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA170',
 'Frankfort Airport',
 '21:54',
 'Cairo Airport',
 '00:58',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA202',
 'Rochester Airport',
 '04:25',
 'Trenton Airport',
 '04:35',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW37',
 'Frankfort Airport',
 '23:41',
 'Worcester Airport',
 '01:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW211',
 'Oklahoma City Airport',
 '12:00',
 'Dayton Airport',
 '12:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir113',
 'Anchorage Airport',
 '15:09',
 'Reading Airport',
 '19:21',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA297',
 'Nkoxville Airport',
 '18:59',
 'Los Angles Airport',
 '19:08',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA139',
 'New York City Airport',
 '11:04',
 'Albany Airport',
 '13:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW172',
 'Burbank Airport',
 '15:17',
 'New Orleans Airport',
 '19:19',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir239',
 'Seattle Airport',
 '02:38',
 'Tacoma Airport',
 '04:49',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA119',
 'Tempa Airport',
 '18:49',
 'St. Louis Airport',
 '22:54',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW197',
 'Dallas Airport',
 '18:48',
 'Los Angles Airport',
 '18:55',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA117',
 'Detroit Airport',
 '11:20',
 'Ann Arbor Airport',
 '12:24',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA178',
 'Raleigh Airport',
 '03:34',
 'San Jose Airport',
 '04:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('UA282',
 'Baltimore Airport',
 '17:57',
 'Syracuse Airport',
 '19:59',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW138',
 'New Orleans Airport',
 '19:06',
 'Atlantic City Airport',
 '20:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA181',
 'Lincoln Airport',
 '19:04',
 'Syracuse Airport',
 '19:15',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir129',
 'Burbank Airport',
 '20:07',
 'Worcester Airport',
 '22:15',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW260',
 'Salt Lake Airport',
 '11:05',
 'Tempa Airport',
 '13:17',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA48',
 'Frankfort Airport',
 '10:03',
 'Charleston Airport',
 '10:04',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL175',
 'Syracuse Airport',
 '04:43',
 'Denver Airport',
 '07:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA53',
 'Salt Lake Airport',
 '12:06',
 'Rochester Airport',
 '15:09',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW26',
 'Albany Airport',
 '02:22',
 'Juneau Airport',
 '05:23',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('TWA58',
 'Minneapolis Airport',
 '02:41',
 'Frankfort Airport',
 '05:53',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA63',
 'Reading Airport',
 '23:24',
 'Atlantic City Airport',
 '02:29',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW180',
 'Phoenix Airport',
 '13:56',
 'Dayton Airport',
 '14:59',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW291',
 'Milwukee Airport',
 '08:30',
 'SpringField Airport',
 '12:43',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW116',
 'Austin Airport',
 '05:52',
 'Pittsburgh Airport',
 '08:01',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta23',
 'Jersey City Airport',
 '10:50',
 'Orlando Airport',
 '14:58',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL18',
 'Cleveland Airport',
 '19:27',
 'Dayton Airport',
 '23:29',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA260',
 'Oakland Airport',
 '18:32',
 'Minneapolis Airport',
 '22:33',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta171',
 'Los Angles Airport',
 '13:33',
 'Indianapolis Airport',
 '16:45',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW271',
 'Sacramento Airport',
 '19:09',
 'Tempa Airport',
 '22:16',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA279',
 'St. Paul Airport',
 '02:29',
 'Austin Airport',
 '03:41',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW182',
 'Orlando Airport',
 '14:47',
 'Tulsa Airport',
 '18:48',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA224',
 'Nashville Airport',
 '10:29',
 'San Diego Airport',
 '13:43',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL60',
 'Trenton Airport',
 '01:43',
 'Athens Airport',
 '06:45',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW210',
 'Houston Airport',
 '16:31',
 'Norfolk Airport',
 '21:34',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW13',
 'Sacramento Airport',
 '16:34',
 'Dayton Airport',
 '17:41',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA175',
 'SpringField Airport',
 '01:27',
 'Green Bay Airport',
 '06:39',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir43',
 'Juneau Airport',
 '01:25',
 'San Diego Airport',
 '02:32',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA41',
 'Minneapolis Airport',
 '12:00',
 'Flint Airport',
 '13:11',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL25',
 'Worcester Airport',
 '00:13',
 'SpringField Airport',
 '03:13',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir59',
 'Raleigh Airport',
 '15:51',
 'Durham Airport',
 '15:02',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA209',
 'Worcester Airport',
 '11:30',
 'Baltimore Airport',
 '12:35',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA19',
 'Cairo Airport',
 '17:55',
 'Houston Airport',
 '21:04',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW275',
 'Norfolk Airport',
 '16:38',
 'Syracuse Airport',
 '20:47',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL14',
 'Nashville Airport',
 '13:44',
 'Jacksonville Airport',
 '17:49',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA55',
 'Juneau Airport',
 '01:53',
 'Ann Arbor Airport',
 '05:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW139',
 'Macon Airport',
 '16:24',
 'Philadelphia Airport',
 '17:38',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AA158',
 'Waco Airport',
 '21:08',
 'Lansing Airport',
 '00:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA247',
 'Charleston Airport',
 '16:03',
 'Athens Airport',
 '20:06',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir290',
 'Tulsa Airport',
 '09:15',
 'San Diego Airport',
 '11:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA7',
 'Minneapolis Airport',
 '18:33',
 'Chicago Airport',
 '22:33',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW145',
 'Richmond Airport',
 '09:49',
 'Philadelphia Airport',
 '09:53',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA115',
 'Salt Lake Airport',
 '08:16',
 'Austin Airport',
 '10:17',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir62',
 'Madison Airport',
 '09:24',
 'Lexington Airport',
 '11:27',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA255',
 'Oklahoma City Airport',
 '00:13',
 'Waco Airport',
 '01:27',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW29',
 'Denver Airport',
 '12:04',
 'Reading Airport',
 '12:07',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('AL202',
 'Austin Airport',
 '09:03',
 'Salt Lake Airport',
 '12:09',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA148',
 'Raleigh Airport',
 '04:50',
 'Austin Airport',
 '08:03',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA123',
 'St. Louis Airport',
 '08:56',
 'Trenton Airport',
 '12:08',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA173',
 'Oklahoma City Airport',
 '11:55',
 'Hershey Airport',
 '15:04',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW170',
 'Macon Airport',
 '13:14',
 'Norfolk Airport',
 '13:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW55',
 'New York City Airport',
 '11:37',
 'Lexington Airport',
 '13:42',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA172',
 'Cincinnati Airport',
 '08:25',
 'Boulder Airport',
 '09:37',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW159',
 'Rochester Airport',
 '14:36',
 'Phoenix Airport',
 '14:43',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('NW196',
 'Boston Airport',
 '03:13',
 'Madison Airport',
 '06:21',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW32',
 'Lexington Airport',
 '16:18',
 'Norfolk Airport',
 '18:32',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA213',
 'Frankfort Airport',
 '16:18',
 'Chicago Airport',
 '18:31',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW137',
 'Sacramento Airport',
 '13:59',
 'St. Paul Airport',
 '14:04',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL160',
 'Los Angles Airport',
 '22:25',
 'Richmond Airport',
 '00:38',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA289',
 'Detroit Airport',
 '23:13',
 'Boston Airport',
 '03:25',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA34',
 'Toledo Airport',
 '23:44',
 'Tacoma Airport',
 '01:44',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA187',
 'Flint Airport',
 '02:18',
 'Dayton Airport',
 '03:31',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA74',
 'Lexington Airport',
 '23:34',
 'Tallahassee Airport',
 '01:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA1',
 'Athens Airport',
 '02:41',
 'Hershey Airport',
 '05:54',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta181',
 'Kansas City Airport',
 '17:59',
 'Boulder Airport',
 '21:02',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AL290',
 'Atlanta Airport',
 '19:02',
 'St. Louis Airport',
 '22:15',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA266',
 'Lexington Airport',
 '20:53',
 'Trenton Airport',
 '21:05',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('TWA175',
 'Anchorage Airport',
 '16:02',
 'San Diego Airport',
 '18:09',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta253',
 'Tulsa Airport',
 '03:57',
 'Indianapolis Airport',
 '05:57',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW143',
 'Juneau Airport',
 '15:55',
 'Oakland Airport',
 '19:59',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir219',
 'Waco Airport',
 '08:24',
 'Salt Lake Airport',
 '09:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL190',
 'Indianapolis Airport',
 '09:46',
 'Nkoxville Airport',
 '14:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA155',
 'Jersey City Airport',
 '18:42',
 'Seattle Airport',
 '20:43',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW204',
 'New York City Airport',
 '20:06',
 'Lexington Airport',
 '01:19',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir188',
 'St. Louis Airport',
 '15:33',
 'Trenton Airport',
 '16:40',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA39',
 'Atlanta Airport',
 '20:34',
 'Los Angles Airport',
 '23:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW156',
 'Tallahassee Airport',
 '09:06',
 'Dayton Airport',
 '12:06',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA171',
 'SpringField Airport',
 '07:25',
 'Brooklyn Airport',
 '11:25',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW63',
 'New Orleans Airport',
 '22:57',
 'Phoenix Airport',
 '01:06',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL234',
 'Syracuse Airport',
 '09:18',
 'New Orleans Airport',
 '10:20',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir241',
 'Indianapolis Airport',
 '15:59',
 'Brooklyn Airport',
 '16:03',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA247',
 'Milwukee Airport',
 '05:27',
 'Dayton Airport',
 '05:28',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL52',
 'Tallahassee Airport',
 '20:09',
 'Athens Airport',
 '22:17',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA63',
 'Tacoma Airport',
 '15:00',
 'Houston Airport',
 '19:14',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA30',
 'Atlantic City Airport',
 '12:56',
 'Phoenix Airport',
 '15:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta69',
 'San Francisco Airport',
 '23:31',
 'San Jose Airport',
 '03:40',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL297',
 'Milwukee Airport',
 '17:27',
 'Atlantic City Airport',
 '18:34',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir92',
 'Frankfort Airport',
 '21:25',
 'Syracuse Airport',
 '23:35',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA30',
 'Portland Airport',
 '22:12',
 'Tallahassee Airport',
 '01:24',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL298',
 'Atlanta Airport',
 '05:52',
 'Buffalo Airport',
 '06:01',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA41',
 'San Diego Airport',
 '13:14',
 'Tallahassee Airport',
 '16:15',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA31',
 'Burbank Airport',
 '00:37',
 'Ann Arbor Airport',
 '04:49',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW163',
 'Rochester Airport',
 '20:56',
 'Charleston Airport',
 '21:03',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir207',
 'Nkoxville Airport',
 '12:26',
 'Dayton Airport',
 '14:32',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW103',
 'Boston Airport',
 '01:02',
 'St. Paul Airport',
 '01:13',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir8',
 'Orlando Airport',
 '21:12',
 'Durham Airport',
 '01:26',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta78',
 'Nkoxville Airport',
 '09:36',
 'Lincoln Airport',
 '12:39',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW21',
 'Atlantic City Airport',
 '20:06',
 'Seattle Airport',
 '22:20',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW173',
 'Burbank Airport',
 '04:57',
 'Durham Airport',
 '09:00',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta29',
 'Boston Airport',
 '02:51',
 'Norfolk Airport',
 '02:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW278',
 'Charleston Airport',
 '01:22',
 'Hershey Airport',
 '05:26',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta75',
 'Dallas Airport',
 '06:28',
 'Charleston Airport',
 '08:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AL109',
 'Dayton Airport',
 '10:56',
 'Waco Airport',
 '13:56',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA216',
 'Phoenix Airport',
 '18:36',
 'Columbus Airport',
 '18:48',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA230',
 'New York City Airport',
 '21:52',
 'SpringField Airport',
 '00:54',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA259',
 'Boulder Airport',
 '15:21',
 'Milwukee Airport',
 '19:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('TWA277',
 'Cincinnati Airport',
 '10:17',
 'Richmond Airport',
 '10:19',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW71',
 'Boulder Airport',
 '07:43',
 'Atlantic City Airport',
 '08:52',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW293',
 'Tulsa Airport',
 '19:39',
 'Anchorage Airport',
 '22:53',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL98',
 'New York City Airport',
 '04:02',
 'Oklahoma City Airport',
 '05:16',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA31',
 'Tulsa Airport',
 '15:55',
 'Indianapolis Airport',
 '19:59',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA112',
 'Dallas Airport',
 '02:53',
 'Phoenix Airport',
 '06:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW75',
 'Austin Airport',
 '06:14',
 'Toledo Airport',
 '08:24',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta231',
 'Buffalo Airport',
 '02:35',
 'Lincoln Airport',
 '03:41',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir17',
 'Jacksonville Airport',
 '23:04',
 'Syracuse Airport',
 '03:04',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL110',
 'Columbus Airport',
 '07:14',
 'San Francisco Airport',
 '11:21',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AL227',
 'New Orleans Airport',
 '03:33',
 'Salt Lake Airport',
 '07:44',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir231',
 'St. Paul Airport',
 '20:21',
 'Detroit Airport',
 '20:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW131',
 'Madison Airport',
 '04:33',
 'Nkoxville Airport',
 '07:40',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW255',
 'Juneau Airport',
 '13:42',
 'Ann Arbor Airport',
 '13:47',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('TWA152',
 'Durham Airport',
 '03:36',
 'Seattle Airport',
 '05:44',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('AA14',
 'New York City Airport',
 '21:35',
 'Toledo Airport',
 '22:39',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir114',
 'Buffalo Airport',
 '21:16',
 'Salt Lake Airport',
 '21:25',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW264',
 'Minneapolis Airport',
 '12:58',
 'Boston Airport',
 '15:59',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta174',
 'Dayton Airport',
 '02:58',
 'Tulsa Airport',
 '06:06',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir53',
 'Brooklyn Airport',
 '20:01',
 'Seattle Airport',
 '20:05',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA275',
 'Sacramento Airport',
 '04:49',
 'Cincinnati Airport',
 '05:51',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta53',
 'Atlantic City Airport',
 '17:21',
 'Athens Airport',
 '21:22',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AL235',
 'Tempa Airport',
 '23:16',
 'Athens Airport',
 '03:17',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA186',
 'Seattle Airport',
 '17:01',
 'San Diego Airport',
 '18:15',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir49',
 'Nkoxville Airport',
 '20:16',
 'Durham Airport',
 '23:30',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('AA85',
 'Sacramento Airport',
 '02:38',
 'Lincoln Airport',
 '02:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW140',
 'Cleveland Airport',
 '00:16',
 'Jacksonville Airport',
 '01:16',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir210',
 'Burbank Airport',
 '11:32',
 'Austin Airport',
 '12:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('CA26',
 'Frankfort Airport',
 '08:52',
 'Tacoma Airport',
 '09:56',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta289',
 'Nashville Airport',
 '15:21',
 'Atlantic City Airport',
 '17:30',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW247',
 'Flint Airport',
 '15:06',
 'Miami Airport',
 '15:11',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW290',
 'Lexington Airport',
 '04:14',
 'Charleston Airport',
 '08:22',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('SW51',
 'Columbus Airport',
 '07:40',
 'Miami Airport',
 '07:54',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta267',
 'Juneau Airport',
 '14:34',
 'Miami Airport',
 '18:43',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA266',
 'Lincoln Airport',
 '02:25',
 'Philadelphia Airport',
 '06:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta214',
 'Miami Airport',
 '17:51',
 'Athens Airport',
 '18:51',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir26',
 'San Antonio Airport',
 '12:49',
 'Oklahoma City Airport',
 '13:52',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir277',
 'San Antonio Airport',
 '17:51',
 'Buffalo Airport',
 '17:58',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta77',
 'Tallahassee Airport',
 '10:55',
 'Dayton Airport',
 '13:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW84',
 'Juneau Airport',
 '20:09',
 'Cairo Airport',
 '00:17',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir45',
 'Dayton Airport',
 '05:23',
 'Indianapolis Airport',
 '09:31',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('USAir266',
 'Dayton Airport',
 '10:10',
 'Milwukee Airport',
 '13:13',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('Delta8',
 'Tallahassee Airport',
 '18:29',
 'Albany Airport',
 '20:34',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('USAir116',
 'Minneapolis Airport',
 '14:15',
 'Memphis Airport',
 '14:19',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA146',
 'Tulsa Airport',
 '22:46',
 'San Diego Airport',
 '23:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA185',
 'Lexington Airport',
 '18:41',
 'Charleston Airport',
 '21:45',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta299',
 'Flint Airport',
 '07:08',
 'Indianapolis Airport',
 '09:12',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta129',
 'Milwukee Airport',
 '19:41',
 'Toledo Airport',
 '19:41',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir143',
 'Tacoma Airport',
 '20:50',
 'Columbus Airport',
 '20:50',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('AA251',
 'Boulder Airport',
 '04:13',
 'Houston Airport',
 '05:14',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('CA236',
 'Memphis Airport',
 '19:41',
 'San Jose Airport',
 '19:42',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir208',
 'Houston Airport',
 '12:27',
 'Chicago Airport',
 '16:28',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW247',
 'Tacoma Airport',
 '07:49',
 'Pittsburgh Airport',
 '07:51',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('Delta4',
 'Miami Airport',
 '13:17',
 'Atlantic City Airport',
 '14:28',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('UA220',
 'Durham Airport',
 '23:13',
 'Baltimore Airport',
 '03:14',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA189',
 'Denver Airport',
 '08:06',
 'Lincoln Airport',
 '09:14',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA107',
 'Philadelphia Airport',
 '02:41',
 'Worcester Airport',
 '03:45',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW91',
 'Austin Airport',
 '14:02',
 'Atlanta Airport',
 '18:09',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA269',
 'Sacramento Airport',
 '06:11',
 'Salt Lake Airport',
 '07:20',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA261',
 'Dayton Airport',
 '06:48',
 'Burbank Airport',
 '06:53',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW81',
 'Denver Airport',
 '03:15',
 'San Antonio Airport',
 '06:20',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA260',
 'Lansing Airport',
 '16:10',
 'Syracuse Airport',
 '18:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('USAir150',
 'Philadelphia Airport',
 '17:23',
 'Indianapolis Airport',
 '20:33',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('CA275',
 'SpringField Airport',
 '05:27',
 'Milwukee Airport',
 '05:29',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('USAir280',
 'Memphis Airport',
 '14:11',
 'Ann Arbor Airport',
 '17:18',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AA104',
 'San Antonio Airport',
 '06:47',
 'Anchorage Airport',
 '07:59',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('Delta229',
 'Green Bay Airport',
 '13:37',
 'Reading Airport',
 '17:50',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW270',
 'Burbank Airport',
 '09:58',
 'Green Bay Airport',
 '09:07',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta153',
 'Phoenix Airport',
 '15:05',
 'Durham Airport',
 '16:10',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('Delta197',
 'Charleston Airport',
 '14:29',
 'Hershey Airport',
 '18:36',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW155',
 'Indianapolis Airport',
 '17:28',
 'Kansas City Airport',
 '18:33',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('NW116',
 'Tempa Airport',
 '14:22',
 'Juneau Airport',
 '17:24',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('CA186',
 'Tacoma Airport',
 '18:44',
 'Brooklyn Airport',
 '21:44',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta144',
 'Oakland Airport',
 '05:24',
 'Waco Airport',
 '08:30',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('AL29',
 'Phoenix Airport',
 '04:17',
 'Toledo Airport',
 '08:29',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta236',
 'Lincoln Airport',
 '05:15',
 'Memphis Airport',
 '07:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta70',
 'Dallas Airport',
 '08:13',
 'Cleveland Airport',
 '08:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('TWA147',
 'Philadelphia Airport',
 '14:46',
 'Boston Airport',
 '14:59',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('SW273',
 'Cairo Airport',
 '07:18',
 'Durham Airport',
 '12:28',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir44',
 'Seattle Airport',
 '16:47',
 'Lincoln Airport',
 '18:56',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW14',
 'Frankfort Airport',
 '07:04',
 'Toledo Airport',
 '11:05',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('UA278',
 'Albany Airport',
 '14:29',
 'Oakland Airport',
 '14:33',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW205',
 'Detroit Airport',
 '08:24',
 'Tempa Airport',
 '12:25',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('SW54',
 'Baltimore Airport',
 '11:38',
 'Cleveland Airport',
 '14:49',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA233',
 'Raleigh Airport',
 '00:12',
 'Cleveland Airport',
 '05:21',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA232',
 'Nkoxville Airport',
 '18:12',
 'Raleigh Airport',
 '20:19',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA278',
 'Charleston Airport',
 '06:27',
 'Indianapolis Airport',
 '10:38',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir48',
 'Miami Airport',
 '07:49',
 'Cincinnati Airport',
 '08:55',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('UA96',
 'Tacoma Airport',
 '23:03',
 'Oklahoma City Airport',
 '01:07',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('Delta19',
 'Los Angles Airport',
 '19:40',
 'Charleston Airport',
 '21:43',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('SW238',
 'Macon Airport',
 '20:50',
 'Atlanta Airport',
 '00:03',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA222',
 'Kansas City Airport',
 '01:40',
 'Tacoma Airport',
 '03:50',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir299',
 'Columbus Airport',
 '04:07',
 'Boulder Airport',
 '05:07',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('USAir245',
 'Pittsburgh Airport',
 '05:55',
 'Chicago Airport',
 '09:56',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW263',
 'Boulder Airport',
 '22:31',
 'Los Angles Airport',
 '00:35',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('USAir284',
 'Macon Airport',
 '04:15',
 'Worcester Airport',
 '04:16',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('NW123',
 'Philadelphia Airport',
 '20:42',
 'Indianapolis Airport',
 '21:46',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('UA114',
 'Toledo Airport',
 '06:22',
 'Durham Airport',
 '08:26',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('UA107',
 'Ann Arbor Airport',
 '19:08',
 'Atlanta Airport',
 '23:22',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW128',
 'Dayton Airport',
 '04:58',
 'Lexington Airport',
 '08:09',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AL104',
 'Lansing Airport',
 '02:03',
 'Philadelphia Airport',
 '05:07',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('SW99',
 'Minneapolis Airport',
 '02:09',
 'Pittsburgh Airport',
 '06:21',
 'Sun');

INSERT INTO FLIGHT_LEG VALUES
('NW184',
 'Charleston Airport',
 '17:43',
 'Kansas City Airport',
 '18:47',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('TWA209',
 'Indianapolis Airport',
 '06:26',
 'Tacoma Airport',
 '06:32',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('NW203',
 'St. Louis Airport',
 '10:12',
 'Lincoln Airport',
 '12:18',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('NW154',
 'New Orleans Airport',
 '10:08',
 'Waco Airport',
 '11:15',
 'Sat');

INSERT INTO FLIGHT_LEG VALUES
('AA108',
 'Jersey City Airport',
 '01:12',
 'Waco Airport',
 '04:20',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('SW229',
 'Portland Airport',
 '20:09',
 'SpringField Airport',
 '00:23',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('USAir6',
 'Tallahassee Airport',
 '08:09',
 'Reading Airport',
 '09:09',
 'Mon');

INSERT INTO FLIGHT_LEG VALUES
('CA145',
 'Phoenix Airport',
 '21:28',
 'Norfolk Airport',
 '01:38',
 'Wed');

INSERT INTO FLIGHT_LEG VALUES
('Delta178',
 'Philadelphia Airport',
 '13:20',
 'Lexington Airport',
 '15:20',
 'Fri');

INSERT INTO FLIGHT_LEG VALUES
('CA261',
 'Houston Airport',
 '10:07',
 'Jacksonville Airport',
 '13:07',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('TWA69',
 'Detroit Airport',
 '22:50',
 'Green Bay Airport',
 '00:02',
 'Thur');

INSERT INTO FLIGHT_LEG VALUES
('NW752',
 'New York City Airport',
 '09:30',
 'Miami Airport',
 '14:48',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('SW420',
 'New York City Airport',
 '07:25',
 'Miami Airport',
 '12:28',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('Delta500',
 'New York City Airport',
 '17:00',
 'Miami Airport',
 '23:28',
 'Tues');

INSERT INTO FLIGHT_LEG VALUES
('AA802',
 'New York City Airport',
 '14:05',
 'Miami Airport',
 '20:45',
 'Tues');

