CREATE TABLE CHECKING
(
 CACCTNUM     CHAR(9)        NOT NULL,
 CBRANCHNUM   INT            NOT NULL,
 CDATEOPEN    DATE           NOT NULL,
 CBALANCE     DECIMAL(11,2)  NOT NULL,
 COVERDRFT    DECIMAL(9,2),
 CHKLIMIT     DECIMAL(7,2),
PRIMARY KEY (CACCTNUM)
);
