CREATE TABLE MEMBERS
(
 MLNAME      VARCHAR(15)    NOT NULL,
 MFNAME      VARCHAR(15)    NOT NULL,
 MMINIT      CHAR,
 MSSN        CHAR(9)        NOT NULL,
 MACCTNO     CHAR(8)        NOT NULL,
 MPHONE      CHAR(10), 
PRIMARY KEY (MSSN, MACCTNO)
);
