CREATE TABLE SAVINGS
(
 SACCTNUM     CHAR(9)        NOT NULL,
 SBRANCHNUM   INT            NOT NULL,
 SDATEOPEN    DATE           NOT NULL,
 SINTRATE     DECIMAL(4,2)   NOT NULL,
 SBALANCE     DECIMAL(11,2)  NOT NULL,
PRIMARY KEY (SACCTNUM)
);
