CREATE TABLE TRANSACTION
(
 TACCT_TYPE       VARCHAR(8)       NOT NULL,
 TACCT_NUM        CHAR(8)          NOT NULL,
 TRANS_DATE       DATE             NOT NULL,
 TRANS_AMT        DECIMAL(9,2)     NOT NULL,
 TRANS_TYPE       CHAR(8)          NOT NULL,
 TRANS_COMMENTS   VARCHAR(40),
PRIMARY KEY (TACCT_TYPE,TACCT_NUM,TRANS_DATE,TRANS_AMT,TRANS_TYPE)
);
